// ****************** sinusfahrtServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtServices__h_INCLUDED
#define _sinusfahrtServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "sinusfahrtVersion.h"
#define SRVNAME_sinusfahrt "sinusfahrt"

// TcCOM-ClassID of CTcComsinusfahrt: {2BE2DEC2-BC85-DC17-1EDA-450CFB49E6B6}
const CTCID CID_SINUSFAHRT = {0x2BE2DEC2, 0xBC85, 0xDC17, {0x1E, 0xDA, 0x45, 0x0C, 0xFB, 0x49, 0xE6, 0xB6}};
// TcCOM-ClassID of CFbsinusfahrt: {BF4DF22A-EB71-FEFF-5121-D715B91B5F03}
const CTCID CID_FB_SINUSFAHRT = {0xBF4DF22A, 0xEB71, 0xFEFF, {0x51, 0x21, 0xD7, 0x15, 0xB9, 0x1B, 0x5F, 0x03}};


#ifndef sinusfahrt_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_CC2F10F1_9954_498E_901C_9CF2D1ECE575_INCLUDED_)
#define _TC_TYPE_CC2F10F1_9954_498E_901C_9CF2D1ECE575_INCLUDED_
typedef struct _sinusfahrt_AdditionalOutports
{
	double TcModuleOutput_vxSLX;
} sinusfahrt_AdditionalOutports, *Psinusfahrt_AdditionalOutports;
#endif // !defined(_TC_TYPE_CC2F10F1_9954_498E_901C_9CF2D1ECE575_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_9412DC90_8B25_D8DB_D7A0_C6C54195D7FB_INCLUDED_)
#define _TC_TYPE_9412DC90_8B25_D8DB_D7A0_C6C54195D7FB_INCLUDED_
typedef struct _B_sinusfahrt_T
{
	double vx;
} B_sinusfahrt_T, *PB_sinusfahrt_T;
#endif // !defined(_TC_TYPE_9412DC90_8B25_D8DB_D7A0_C6C54195D7FB_INCLUDED_)

#if !defined(_TC_TYPE_8DE35575_0915_36DA_F5A4_C4B62DBA5824_INCLUDED_)
#define _TC_TYPE_8DE35575_0915_36DA_F5A4_C4B62DBA5824_INCLUDED_
typedef struct _sinusfahrt_sinusfahrt_DW1_Type
{
	LONG counter;
} sinusfahrt_sinusfahrt_DW1_Type, *Psinusfahrt_sinusfahrt_DW1_Type;
#endif // !defined(_TC_TYPE_8DE35575_0915_36DA_F5A4_C4B62DBA5824_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("4DD802F9-894A-47A6-1BF5-43FFA7657806", ITcsinusfahrt)



#endif // _sinusfahrtServices__h_INCLUDED
