
// ****************** sinusfahrtCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtCtrl__h_INCLUDED
#define _sinusfahrtCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CsinusfahrtDrvName "sinusfahrt"

#include "sinusfahrtW32Resource.h"
#include "sinusfahrtW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "sinusfahrtClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CsinusfahrtCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CsinusfahrtCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CsinusfahrtCtrl, CsinusfahrtClassFactory>
{
public:
	CsinusfahrtCtrl() : ITcOCFCtrlImpl<CsinusfahrtCtrl, CsinusfahrtClassFactory>(){}

	virtual ~CsinusfahrtCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_sinusfahrtCtrl)
DECLARE_NOT_AGGREGATABLE(CsinusfahrtCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CsinusfahrtCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _sinusfahrtCtrl__h_INCLUDED