
// ****************** sinusfahrtClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "sinusfahrtClassFactory.h"
#include "sinusfahrtServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComsinusfahrt (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbsinusfahrt);


DEFINE_REPOSITORY_DRIVER(CsinusfahrtClassFactory, sinusfahrt_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CsinusfahrtClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_sinusfahrt,CID_SINUSFAHRT, SRVNAME_sinusfahrt "!CTcComsinusfahrt", Create_CTcComsinusfahrt)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CsinusfahrtClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbsinusfahrt)

END_FUNC_MAP()

CsinusfahrtClassFactory::CsinusfahrtClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_sinusfahrt)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_sinusfahrt));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(sinusfahrt));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CsinusfahrtClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			