// ****************** sinusfahrtInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtInterfaces__h_INCLUDED
#define _sinusfahrtInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "sinusfahrtServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_4DD802F9_894A_47A6_1BF5_43FFA7657806_INCLUDED_)
#define _TC_TYPE_4DD802F9_894A_47A6_1BF5_43FFA7657806_INCLUDED_
struct __declspec(novtable) ITcsinusfahrt : ITcUnknown 
{
	virtual HRESULT TCOMAPI sinusfahrt_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcsinusfahrt, IID_ITcsinusfahrt);
#endif // !defined(_TC_TYPE_4DD802F9_894A_47A6_1BF5_43FFA7657806_INCLUDED_)



#endif // _sinusfahrtInterfaces__h_INCLUDED
