// ****************** sinusfahrtDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtDuts__h_INCLUDED
#define _sinusfahrtDuts__h_INCLUDED
#include "sinusfahrtServices.h"

#if defined(_X86_)
typedef struct _ST_FB_init_FB_sinusfahrt
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1;
} ST_FB_init_FB_sinusfahrt, *PST_FB_init_FB_sinusfahrt;
#elif defined(_X64_)
typedef struct _ST_FB_init_FB_sinusfahrt
{
	PVOID pInst;
	bool bInitRetains;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[5];
} ST_FB_init_FB_sinusfahrt, *PST_FB_init_FB_sinusfahrt;
#endif

#if defined(_X86_)
typedef struct _ST_FB_Main_FB_sinusfahrt
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[3];
} ST_FB_Main_FB_sinusfahrt, *PST_FB_Main_FB_sinusfahrt;
#elif defined(_X64_)
typedef struct _ST_FB_Main_FB_sinusfahrt
{
	PVOID pInst;
	bool result;
	unsigned char reserved1[7];
} ST_FB_Main_FB_sinusfahrt, *PST_FB_Main_FB_sinusfahrt;
#endif

#if defined(_X86_)
typedef struct _ST_FB_exit_FB_sinusfahrt
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[2];
} ST_FB_exit_FB_sinusfahrt, *PST_FB_exit_FB_sinusfahrt;
#elif defined(_X64_)
typedef struct _ST_FB_exit_FB_sinusfahrt
{
	PVOID pInst;
	bool bInCopyCode;
	bool result;
	unsigned char reserved1[6];
} ST_FB_exit_FB_sinusfahrt, *PST_FB_exit_FB_sinusfahrt;
#endif



#endif // _sinusfahrtDuts__h_INCLUDED
