// ****************** sinusfahrtInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtInternal__h_INCLUDED
#define _sinusfahrtInternal__h_INCLUDED

#include "rtwtypes.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "sinusfahrt.h"
#include "sinusfahrt_private.h"
#include "sinusfahrt_types.h"


// B_sinusfahrt_T
#ifndef _TC_TYPE_9412DC90_8B25_D8DB_D7A0_C6C54195D7FB_INCLUDED_
#define _TC_TYPE_9412DC90_8B25_D8DB_D7A0_C6C54195D7FB_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_sinusfahrt_T,8);

// DW_sinusfahrt_T
#ifndef _TC_TYPE_8BEDAD6A_0E16_932A_776C_D5CCC3FDFD53_INCLUDED_
#define _TC_TYPE_8BEDAD6A_0E16_932A_776C_D5CCC3FDFD53_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_sinusfahrt_T,8,16);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

#endif // _sinusfahrtInternal__h_INCLUDED