
// ****************** sinusfahrtDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _sinusfahrtDrv__h_INCLUDED
#define _sinusfahrtDrv__h_INCLUDED

#include "TcPch.h"

#define sinusfahrtDRV_NAME			"sinusfahrt"
#define sinusfahrtDRV_Major			1
#define sinusfahrtDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CsinusfahrtDrv

#include "ObjDriver.h"

class CsinusfahrtDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl sinusfahrt_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( sinusfahrtDRV)
	VxD_Service( sinusfahrt_GetVersion		)
End_VxD_Service_Table


#endif // _sinusfahrtDrv__h_INCLUDED