
// ****************** A_searchClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "A_searchClassFactory.h"
#include "A_searchServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComA_search (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbA_search);


DEFINE_REPOSITORY_DRIVER(CA_searchClassFactory, A_search_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CA_searchClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_A_search,CID_A_SEARCH, SRVNAME_A_search "!CTcComA_search", Create_CTcComA_search)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CA_searchClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbA_search)

END_FUNC_MAP()

CA_searchClassFactory::CA_searchClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_A_search)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_A_search));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(A_search));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CA_searchClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			