
// ****************** A_searchDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_searchDrv__h_INCLUDED
#define _A_searchDrv__h_INCLUDED

#include "TcPch.h"

#define A_searchDRV_NAME			"A_search"
#define A_searchDRV_Major			1
#define A_searchDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CA_searchDrv

#include "ObjDriver.h"

class CA_searchDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl A_search_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( A_searchDRV)
	VxD_Service( A_search_GetVersion		)
End_VxD_Service_Table


#endif // _A_searchDrv__h_INCLUDED