// ****************** A_searchInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_searchInternal__h_INCLUDED
#define _A_searchInternal__h_INCLUDED

#include "rtwtypes.h"
#include "rtGetInf.h"
#include "rtGetNaN.h"
#include "rt_nonfinite.h"
#include "A_search.h"
#include "A_search_private.h"
#include "A_search_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// B_A_search_T
#ifndef _TC_TYPE_7FE958DA_B089_5205_4961_627A831175F7_INCLUDED_
#define _TC_TYPE_7FE958DA_B089_5205_4961_627A831175F7_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_A_search_T,13672);

// DW_A_search_T
#ifndef _TC_TYPE_290DD403_5137_B203_EC1C_181CCAC0CE40_INCLUDED_
#define _TC_TYPE_290DD403_5137_B203_EC1C_181CCAC0CE40_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_A_search_T,32,64);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// cell_wrap_0_A_search_T
#ifndef _TC_TYPE_D037FBEF_4F1B_6498_2A7F_255255A687AF_INCLUDED_
#define _TC_TYPE_D037FBEF_4F1B_6498_2A7F_255255A687AF_INCLUDED_
#endif
TYPESIZE_VALIDATION(cell_wrap_0_A_search_T,3208);

// emxArray_real_T_400_A_search_T
#ifndef _TC_TYPE_B2326C34_7466_CAFD_97D6_5A186226E2AD_INCLUDED_
#define _TC_TYPE_B2326C34_7466_CAFD_97D6_5A186226E2AD_INCLUDED_
#endif
TYPESIZE_VALIDATION(emxArray_real_T_400_A_search_T,3208);

#endif // _A_searchInternal__h_INCLUDED