// ****************** A_searchInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_searchInterfaces__h_INCLUDED
#define _A_searchInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "A_searchServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_AEF3033C_3B88_CAE1_E14A_A8D52BB03DF9_INCLUDED_)
#define _TC_TYPE_AEF3033C_3B88_CAE1_E14A_A8D52BB03DF9_INCLUDED_
struct __declspec(novtable) ITcA_search : ITcUnknown 
{
	virtual HRESULT TCOMAPI A_search_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcA_search, IID_ITcA_search);
#endif // !defined(_TC_TYPE_AEF3033C_3B88_CAE1_E14A_A8D52BB03DF9_INCLUDED_)



#endif // _A_searchInterfaces__h_INCLUDED
