// ****************** A_searchW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "A_searchCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_A_searchCtrl		=  {0x5D2179D3, 0xFCB0, 0x4818, {0xA5, 0x40, 0xB4, 0x28, 0xEA, 0xAE, 0x14, 0x04}};
const   CLSID   LIBID_A_searchW32Lib	=  {0xB1A66ACD, 0x0F00, 0x47EF, {0xA4, 0xD2, 0xF0, 0xC2, 0x28, 0x24, 0x0C, 0x85}};
const   CLSID   CLSID_A_searchCtrl   =  {0xC8001EA9, 0x1F65, 0x40B8, {0xBA, 0x8C, 0x2E, 0x45, 0x99, 0xA6, 0x26, 0x7B}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_A_searchCtrl, CA_searchCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CA_searchCtrl>* pCA_searchCtrl = new CComObject<CA_searchCtrl>();
	if (pCA_searchCtrl == NULL) return E_POINTER;
	return pCA_searchCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
