
// ****************** A_searchCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_searchCtrl__h_INCLUDED
#define _A_searchCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CA_searchDrvName "A_search"

#include "A_searchW32Resource.h"
#include "A_searchW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "A_searchClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CA_searchCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CA_searchCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CA_searchCtrl, CA_searchClassFactory>
{
public:
	CA_searchCtrl() : ITcOCFCtrlImpl<CA_searchCtrl, CA_searchClassFactory>(){}

	virtual ~CA_searchCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_A_searchCtrl)
DECLARE_NOT_AGGREGATABLE(CA_searchCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CA_searchCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _A_searchCtrl__h_INCLUDED