// ****************** A_searchServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_searchServices__h_INCLUDED
#define _A_searchServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "A_searchVersion.h"
#define SRVNAME_A_search "A_search"

// TcCOM-ClassID of CTcComA_search: {E8159DBE-F88B-7273-C6B3-6E0BE540CBDA}
const CTCID CID_A_SEARCH = {0xE8159DBE, 0xF88B, 0x7273, {0xC6, 0xB3, 0x6E, 0x0B, 0xE5, 0x40, 0xCB, 0xDA}};
// TcCOM-ClassID of CFbA_search: {DD518107-48FC-A765-CF69-F51F994970E3}
const CTCID CID_FB_A_SEARCH = {0xDD518107, 0x48FC, 0xA765, {0xCF, 0x69, 0xF5, 0x1F, 0x99, 0x49, 0x70, 0xE3}};


#ifndef A_search_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_C20C1945_7021_E831_DB57_660F028D6669_INCLUDED_)
#define _TC_TYPE_C20C1945_7021_E831_DB57_660F028D6669_INCLUDED_
typedef struct _A_search_AdditionalInports
{
	double TcModuleInput_TCModuleInput1;
	double TcModuleInput_TCModuleInput2;
	double TcModuleInput_TCModuleInput3;
	double TcModuleInput_TCModuleInput4;
	double TcModuleInput_TCModuleInput5;
	double TcModuleInput_TCModuleInput6;
} A_search_AdditionalInports, *PA_search_AdditionalInports;
#endif // !defined(_TC_TYPE_C20C1945_7021_E831_DB57_660F028D6669_INCLUDED_)

#if !defined(_TC_TYPE_A49527D2_51AB_87DD_5639_CD05690B713C_INCLUDED_)
#define _TC_TYPE_A49527D2_51AB_87DD_5639_CD05690B713C_INCLUDED_
typedef double matrix_20_real_T[20];
#endif // !defined(_TC_TYPE_A49527D2_51AB_87DD_5639_CD05690B713C_INCLUDED_)

#if !defined(_TC_TYPE_3EF30FBF_3C3F_5638_311A_AF9C1312D63C_INCLUDED_)
#define _TC_TYPE_3EF30FBF_3C3F_5638_311A_AF9C1312D63C_INCLUDED_
typedef struct _A_search_AdditionalOutports
{
	matrix_20_real_T TcModuleOutput_TCModuleOutput;
	matrix_20_real_T TcModuleOutput_TCModuleOutput1;
} A_search_AdditionalOutports, *PA_search_AdditionalOutports;
#endif // !defined(_TC_TYPE_3EF30FBF_3C3F_5638_311A_AF9C1312D63C_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_A67C9D9D_6318_6223_5F84_B60D4C18E5C1_INCLUDED_)
#define _TC_TYPE_A67C9D9D_6318_6223_5F84_B60D4C18E5C1_INCLUDED_
typedef double matrix_400_real_T[400];
#endif // !defined(_TC_TYPE_A67C9D9D_6318_6223_5F84_B60D4C18E5C1_INCLUDED_)

#if !defined(_TC_TYPE_B2326C34_7466_CAFD_97D6_5A186226E2AD_INCLUDED_)
#define _TC_TYPE_B2326C34_7466_CAFD_97D6_5A186226E2AD_INCLUDED_
typedef struct _emxArray_real_T_400_A_search_T
{
	matrix_400_real_T data;
	LONG size;
	unsigned char reserved1[4];
} emxArray_real_T_400_A_search_T, *PemxArray_real_T_400_A_search_T;
#endif // !defined(_TC_TYPE_B2326C34_7466_CAFD_97D6_5A186226E2AD_INCLUDED_)

#if !defined(_TC_TYPE_D037FBEF_4F1B_6498_2A7F_255255A687AF_INCLUDED_)
#define _TC_TYPE_D037FBEF_4F1B_6498_2A7F_255255A687AF_INCLUDED_
typedef struct _cell_wrap_0_A_search_T
{
	emxArray_real_T_400_A_search_T f1;
} cell_wrap_0_A_search_T, *Pcell_wrap_0_A_search_T;
#endif // !defined(_TC_TYPE_D037FBEF_4F1B_6498_2A7F_255255A687AF_INCLUDED_)

#if !defined(_TC_TYPE_7FE958DA_B089_5205_4961_627A831175F7_INCLUDED_)
#define _TC_TYPE_7FE958DA_B089_5205_4961_627A831175F7_INCLUDED_
typedef struct _B_A_search_T
{
	cell_wrap_0_A_search_T Graph_EdgeProperties_data;
	cell_wrap_0_A_search_T q;
	matrix_400_real_T expl_temp_data;
	double TCModuleInput1;
	double TCModuleInput2;
	double TCModuleInput3;
	double TCModuleInput4;
	double TCModuleInput5;
	double TCModuleInput6;
	matrix_20_real_T xKoordinaten;
	matrix_20_real_T yKoordinaten;
	double startKnoten;
	matrix_400_real_T A;
	matrix_20_real_T xKnoten;
	matrix_20_real_T yKnoten;
	matrix_20_real_T wayPointList;
} B_A_search_T, *PB_A_search_T;
#endif // !defined(_TC_TYPE_7FE958DA_B089_5205_4961_627A831175F7_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("AEF3033C-3B88-CAE1-E14A-A8D52BB03DF9", ITcA_search)



#endif // _A_searchServices__h_INCLUDED
