
// ****************** FbA_search.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbA_search__h_INCLUDED
#define _FbA_search__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "A_searchInternal.h"

#include "A_searchDuts.h"
#include "A_searchInterfaces.h"
#include "A_searchVersion.h"

class CFbA_search :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_A_search;}
	inline CLSID get_ClassID() {return CID_FB_A_SEARCH;}

	DECLARE_FUNC_MAP_FB()

	CFbA_search();
	~CFbA_search();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_A_search* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_A_search* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_A_search* ST_Param);


	double TcModuleInput_TCModuleInput1;
	double TcModuleInput_TCModuleInput2;
	double TcModuleInput_TCModuleInput3;
	double TcModuleInput_TCModuleInput4;
	double TcModuleInput_TCModuleInput5;
	double TcModuleInput_TCModuleInput6;
	matrix_20_real_T TcModuleOutput_TCModuleOutput;
	matrix_20_real_T TcModuleOutput_TCModuleOutput1;
	PVOID PA_search_M;


};
TYPESIZE_VALIDATION2(CFbA_search,384,392);

			
#endif // _FbA_search__h_INCLUDED
			