// ****************** DraftSimpleEstimatorANDControlServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _DraftSimpleEstimatorANDControlServices__h_INCLUDED
#define _DraftSimpleEstimatorANDControlServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "DraftSimpleEstimatorANDControlVersion.h"
#define SRVNAME_DraftSimpleEstimatorANDControl "DraftSimpleEstimatorANDControl"

// TcCOM-ClassID of CTcComDraftSimpleEstimatorANDControl: {911CD842-4C90-BEC1-4FAF-72A6D7F74511}
const CTCID CID_DRAFTSIMPLEESTIMATORANDCONTROL = {0x911CD842, 0x4C90, 0xBEC1, {0x4F, 0xAF, 0x72, 0xA6, 0xD7, 0xF7, 0x45, 0x11}};
// TcCOM-ClassID of CFbDraftSimpleEstimatorANDControl: {6EE02854-8CB0-6F4B-F004-FC47A9709690}
const CTCID CID_FB_DRAFTSIMPLEESTIMATORANDCONTROL = {0x6EE02854, 0x8CB0, 0x6F4B, {0xF0, 0x04, 0xFC, 0x47, 0xA9, 0x70, 0x96, 0x90}};


#ifndef DraftSimpleEstimatorANDControl_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)
#define _TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_
typedef double matrix_3_real_T[3];
#endif // !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)

#if !defined(_TC_TYPE_31ECAE2B_4CBF_E714_8B62_B3F18478CB54_INCLUDED_)
#define _TC_TYPE_31ECAE2B_4CBF_E714_8B62_B3F18478CB54_INCLUDED_
typedef struct _DraftSimpleEstimatorANDControl_AdditionalInports
{
	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InContrID;
	double TcModuleInput_InContrIN;
	double TcModuleInput_InContrP;
	double TcModuleInput_InContrlI;
	matrix_3_real_T TcModuleInput_InNextWaypoint;
	double TcModuleInput_InVThetafromMotors;
	double TcModuleInput_InVXfromMotors;
	double TcModuleInput_InVYfromMotors;
} DraftSimpleEstimatorANDControl_AdditionalInports, *PDraftSimpleEstimatorANDControl_AdditionalInports;
#endif // !defined(_TC_TYPE_31ECAE2B_4CBF_E714_8B62_B3F18478CB54_INCLUDED_)

#if !defined(_TC_TYPE_3B392646_2E84_68D2_B6DC_82EFC8FB7ABA_INCLUDED_)
#define _TC_TYPE_3B392646_2E84_68D2_B6DC_82EFC8FB7ABA_INCLUDED_
typedef struct _DraftSimpleEstimatorANDControl_AdditionalOutports
{
	matrix_3_real_T TcModuleOutput_Estimator1_vMotors;
	matrix_3_real_T TcModuleOutput_Estimator1_vWorld;
	double TcModuleOutput_OutDebugCase;
	matrix_3_real_T TcModuleOutput_OutErrorPose;
	double TcModuleOutput_OutEstTheta;
	double TcModuleOutput_OutEstX;
	double TcModuleOutput_OutEstY;
	matrix_3_real_T TcModuleOutput_OutVtoMotors;
} DraftSimpleEstimatorANDControl_AdditionalOutports, *PDraftSimpleEstimatorANDControl_AdditionalOutports;
#endif // !defined(_TC_TYPE_3B392646_2E84_68D2_B6DC_82EFC8FB7ABA_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_5C43C625_CF5F_F401_2B34_63EB0492A253_INCLUDED_)
#define _TC_TYPE_5C43C625_CF5F_F401_2B34_63EB0492A253_INCLUDED_
typedef struct _B_DraftSimpleEstimatorANDCont_T
{
	matrix_3_real_T InNextWaypoint;
	matrix_3_real_T InCameraPose;
	matrix_3_real_T CameraPOse;
	matrix_3_real_T Odometry;
	matrix_3_real_T DelayOneStep1;
	matrix_3_real_T Subtract2;
	matrix_3_real_T CameraDelay;
	matrix_3_real_T Subtract1;
	matrix_3_real_T ErrorPose;
	double InVXfromMotors;
	double InVYfromMotors;
	double InVThetafromMotors;
	matrix_3_real_T Transpose;
	double InContrID;
	double InContrIN;
	double InContrP;
	double InContrlI;
	matrix_3_real_T TmpSignalConversionAtOutVtoMoto;
	matrix_3_real_T velR;
	matrix_3_real_T velW;
	matrix_3_real_T estimatedPose;
	double debug;
	double estimatedX;
	double estimatedY;
	double estimatedTheta;
	matrix_3_real_T TmpSignalConversionAtTransposeI;
	double Saturation;
	double Saturation1;
	double Saturation2;
	matrix_3_real_T Transpose_p;
	bool newCamDataArrived;
	unsigned char reserved1[7];
} B_DraftSimpleEstimatorANDCont_T, *PB_DraftSimpleEstimatorANDCont_T;
#endif // !defined(_TC_TYPE_5C43C625_CF5F_F401_2B34_63EB0492A253_INCLUDED_)

#if !defined(_TC_TYPE_C75FF49A_E962_9508_5433_F572CA418297_INCLUDED_)
#define _TC_TYPE_C75FF49A_E962_9508_5433_F572CA418297_INCLUDED_
typedef struct _X_DraftSimpleEstimatorANDCont_T
{
	matrix_3_real_T Integrator_CSTATE;
} X_DraftSimpleEstimatorANDCont_T, *PX_DraftSimpleEstimatorANDCont_T;
#endif // !defined(_TC_TYPE_C75FF49A_E962_9508_5433_F572CA418297_INCLUDED_)

#if !defined(_TC_TYPE_D66A6CF3_92AF_F198_AE29_9C504D923AF2_INCLUDED_)
#define _TC_TYPE_D66A6CF3_92AF_F198_AE29_9C504D923AF2_INCLUDED_
typedef double matrix_42_real_T[42];
#endif // !defined(_TC_TYPE_D66A6CF3_92AF_F198_AE29_9C504D923AF2_INCLUDED_)

#if !defined(_TC_TYPE_B000E83D_CB50_34C8_EA24_FAF7E8D9A695_INCLUDED_)
#define _TC_TYPE_B000E83D_CB50_34C8_EA24_FAF7E8D9A695_INCLUDED_
typedef struct _DraftSimpleEstimatorANDControl_DraftSimpleEstimatorANDContr_DW1_Type
{
	matrix_3_real_T DelayOneStep1_DSTATE;
	matrix_42_real_T CameraDelay_DSTATE;
	matrix_3_real_T estPoseOld;
	matrix_3_real_T oldCamData;
} DraftSimpleEstimatorANDControl_DraftSimpleEstimatorANDContr_DW1_Type, *PDraftSimpleEstimatorANDControl_DraftSimpleEstimatorANDContr_DW1_Type;
#endif // !defined(_TC_TYPE_B000E83D_CB50_34C8_EA24_FAF7E8D9A695_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("17CDD510-CD8F-4C53-4302-7259B2097677", ITcDraftSimpleEstimatorANDControl)



#endif // _DraftSimpleEstimatorANDControlServices__h_INCLUDED
