// ****************** DraftSimpleEstimatorANDControlW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "DraftSimpleEstimatorANDControlCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_DraftSimpleEstimatorANDControlCtrl		=  {0xE2F8394E, 0x20B3, 0x4147, {0xAE, 0xFF, 0x7E, 0x23, 0xFA, 0xCE, 0x50, 0x66}};
const   CLSID   LIBID_DraftSimpleEstimatorANDControlW32Lib	=  {0x3A7897D4, 0x2E95, 0x41FF, {0x98, 0x3B, 0x5A, 0x74, 0xF7, 0x15, 0x64, 0x84}};
const   CLSID   CLSID_DraftSimpleEstimatorANDControlCtrl   =  {0xBDB482FF, 0xAB02, 0x4FFB, {0xB6, 0xA8, 0x0E, 0x77, 0xBD, 0x9E, 0x54, 0x66}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_DraftSimpleEstimatorANDControlCtrl, CDraftSimpleEstimatorANDControlCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CDraftSimpleEstimatorANDControlCtrl>* pCDraftSimpleEstimatorANDControlCtrl = new CComObject<CDraftSimpleEstimatorANDControlCtrl>();
	if (pCDraftSimpleEstimatorANDControlCtrl == NULL) return E_POINTER;
	return pCDraftSimpleEstimatorANDControlCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
