// ****************** DraftSimpleEstimatorANDControlInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _DraftSimpleEstimatorANDControlInterfaces__h_INCLUDED
#define _DraftSimpleEstimatorANDControlInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "DraftSimpleEstimatorANDControlServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_17CDD510_CD8F_4C53_4302_7259B2097677_INCLUDED_)
#define _TC_TYPE_17CDD510_CD8F_4C53_4302_7259B2097677_INCLUDED_
struct __declspec(novtable) ITcDraftSimpleEstimatorANDControl : ITcUnknown 
{
	virtual HRESULT TCOMAPI DraftSimpleEstimatorANDControl_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcDraftSimpleEstimatorANDControl, IID_ITcDraftSimpleEstimatorANDControl);
#endif // !defined(_TC_TYPE_17CDD510_CD8F_4C53_4302_7259B2097677_INCLUDED_)



#endif // _DraftSimpleEstimatorANDControlInterfaces__h_INCLUDED
