
// ****************** DraftSimpleEstimatorANDControlClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "DraftSimpleEstimatorANDControlClassFactory.h"
#include "DraftSimpleEstimatorANDControlServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComDraftSimpleEstimatorANDControl (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbDraftSimpleEstimatorANDControl);


DEFINE_REPOSITORY_DRIVER(CDraftSimpleEstimatorANDControlClassFactory, DraftSimpleEstimatorANDControl_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CDraftSimpleEstimatorANDControlClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_DraftSimpleEstimatorANDControl,CID_DRAFTSIMPLEESTIMATORANDCONTROL, SRVNAME_DraftSimpleEstimatorANDControl "!CTcComDraftSimpleEstimatorANDControl", Create_CTcComDraftSimpleEstimatorANDControl)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CDraftSimpleEstimatorANDControlClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbDraftSimpleEstimatorANDControl)

END_FUNC_MAP()

CDraftSimpleEstimatorANDControlClassFactory::CDraftSimpleEstimatorANDControlClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_DraftSimpleEstimatorANDControl)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_DraftSimpleEstimatorANDControl));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(DraftSimpleEstimatorANDControl));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CDraftSimpleEstimatorANDControlClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			