
// ****************** DraftSimpleEstimatorANDControlCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _DraftSimpleEstimatorANDControlCtrl__h_INCLUDED
#define _DraftSimpleEstimatorANDControlCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CDraftSimpleEstimatorANDControlDrvName "DraftSimpleEstimatorANDControl"

#include "DraftSimpleEstimatorANDControlW32Resource.h"
#include "DraftSimpleEstimatorANDControlW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "DraftSimpleEstimatorANDControlClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CDraftSimpleEstimatorANDControlCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CDraftSimpleEstimatorANDControlCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CDraftSimpleEstimatorANDControlCtrl, CDraftSimpleEstimatorANDControlClassFactory>
{
public:
	CDraftSimpleEstimatorANDControlCtrl() : ITcOCFCtrlImpl<CDraftSimpleEstimatorANDControlCtrl, CDraftSimpleEstimatorANDControlClassFactory>(){}

	virtual ~CDraftSimpleEstimatorANDControlCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_DraftSimpleEstimatorANDControlCtrl)
DECLARE_NOT_AGGREGATABLE(CDraftSimpleEstimatorANDControlCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CDraftSimpleEstimatorANDControlCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _DraftSimpleEstimatorANDControlCtrl__h_INCLUDED