// ****************** DraftSimpleEstimatorANDControlInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _DraftSimpleEstimatorANDControlInternal__h_INCLUDED
#define _DraftSimpleEstimatorANDControlInternal__h_INCLUDED

#include "rtwtypes.h"
#include "DraftSimpleEstimatorANDControl.h"
#include "DraftSimpleEstimatorANDControl_private.h"
#include "DraftSimpleEstimatorANDControl_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// B_DraftSimpleEstimatorANDCont_T
#ifndef _TC_TYPE_5C43C625_CF5F_F401_2B34_63EB0492A253_INCLUDED_
#define _TC_TYPE_5C43C625_CF5F_F401_2B34_63EB0492A253_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_DraftSimpleEstimatorANDCont_T,504);

// DW_DraftSimpleEstimatorANDCon_T
#ifndef _TC_TYPE_52F2C5E8_5CCE_D259_91C5_9D191271E130_INCLUDED_
#define _TC_TYPE_52F2C5E8_5CCE_D259_91C5_9D191271E130_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_DraftSimpleEstimatorANDCon_T,480,544);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// X_DraftSimpleEstimatorANDCont_T
#ifndef _TC_TYPE_C75FF49A_E962_9508_5433_F572CA418297_INCLUDED_
#define _TC_TYPE_C75FF49A_E962_9508_5433_F572CA418297_INCLUDED_
#endif
TYPESIZE_VALIDATION(X_DraftSimpleEstimatorANDCont_T,24);

#endif // _DraftSimpleEstimatorANDControlInternal__h_INCLUDED