
// ****************** DraftSimpleEstimatorANDControlDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "DraftSimpleEstimatorANDControlDrv.h"
#include "DraftSimpleEstimatorANDControlClassFactory.h"
#include "DraftSimpleEstimatorANDControlVersion.h"

DECLARE_GENERIC_DEVICE(DraftSimpleEstimatorANDControlDRV)
#undef DEVICE_MAIN

IOSTATUS CDraftSimpleEstimatorANDControlDrv::OnLoad( )
{
	TRACE(_T("CDraftSimpleEstimatorANDControlClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CDraftSimpleEstimatorANDControlClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CDraftSimpleEstimatorANDControlDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CDraftSimpleEstimatorANDControlDrv::DraftSimpleEstimatorANDControl_GetVersion( )
{
	return(0);
}