
// ****************** FbDraftSimpleEstimatorANDControl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbDraftSimpleEstimatorANDControl__h_INCLUDED
#define _FbDraftSimpleEstimatorANDControl__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "DraftSimpleEstimatorANDControlInternal.h"

#include "DraftSimpleEstimatorANDControlDuts.h"
#include "DraftSimpleEstimatorANDControlInterfaces.h"
#include "DraftSimpleEstimatorANDControlVersion.h"

class CFbDraftSimpleEstimatorANDControl :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_DraftSimpleEstimatorANDControl;}
	inline CLSID get_ClassID() {return CID_FB_DRAFTSIMPLEESTIMATORANDCONTROL;}

	DECLARE_FUNC_MAP_FB()

	CFbDraftSimpleEstimatorANDControl();
	~CFbDraftSimpleEstimatorANDControl();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_DraftSimpleEstimatorANDControl* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_DraftSimpleEstimatorANDControl* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_DraftSimpleEstimatorANDControl* ST_Param);


	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InContrID;
	double TcModuleInput_InContrIN;
	double TcModuleInput_InContrP;
	double TcModuleInput_InContrlI;
	matrix_3_real_T TcModuleInput_InNextWaypoint;
	double TcModuleInput_InVThetafromMotors;
	double TcModuleInput_InVXfromMotors;
	double TcModuleInput_InVYfromMotors;
	matrix_3_real_T TcModuleOutput_Estimator1_vMotors;
	matrix_3_real_T TcModuleOutput_Estimator1_vWorld;
	double TcModuleOutput_OutDebugCase;
	matrix_3_real_T TcModuleOutput_OutErrorPose;
	double TcModuleOutput_OutEstTheta;
	double TcModuleOutput_OutEstX;
	double TcModuleOutput_OutEstY;
	matrix_3_real_T TcModuleOutput_OutVtoMotors;
	PVOID PDraftSimpleEstimatorANDContr_M;


};
TYPESIZE_VALIDATION2(CFbDraftSimpleEstimatorANDControl,248,256);

			
#endif // _FbDraftSimpleEstimatorANDControl__h_INCLUDED
			