// ****************** A_search_2021bInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_search_2021bInterfaces__h_INCLUDED
#define _A_search_2021bInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "A_search_2021bServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_78189268_4DCA_E0BC_718B_D361EFD0087C_INCLUDED_)
#define _TC_TYPE_78189268_4DCA_E0BC_718B_D361EFD0087C_INCLUDED_
struct __declspec(novtable) ITcA_search_2021b : ITcUnknown 
{
	virtual HRESULT TCOMAPI step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcA_search_2021b, IID_ITcA_search_2021b);
#endif // !defined(_TC_TYPE_78189268_4DCA_E0BC_718B_D361EFD0087C_INCLUDED_)



#endif // _A_search_2021bInterfaces__h_INCLUDED
