
// ****************** A_search_2021bClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "A_search_2021bClassFactory.h"
#include "A_search_2021bServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComA_search_2021b (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbA_search_2021b);


DEFINE_REPOSITORY_DRIVER(CA_search_2021bClassFactory, A_search_2021b_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CA_search_2021bClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_A_search_2021b,CID_A_SEARCH_2021B, SRVNAME_A_search_2021b "!CTcComA_search_2021b", Create_CTcComA_search_2021b)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CA_search_2021bClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbA_search_2021b)

END_FUNC_MAP()

CA_search_2021bClassFactory::CA_search_2021bClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_A_search_2021b)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_A_search_2021b));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(A_search_2021b));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CA_search_2021bClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			