// ****************** A_search_2021bInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_search_2021bInternal__h_INCLUDED
#define _A_search_2021bInternal__h_INCLUDED

#include "rtwtypes.h"
#include "rtGetInf.h"
#include "rtGetNaN.h"
#include "rt_nonfinite.h"
#include "A_search_2021b.h"
#include "A_search_2021b_private.h"
#include "A_search_2021b_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// B_A_search_2021b_T
#ifndef _TC_TYPE_61FE304E_1B95_43AD_04F3_86A2FA0CF572_INCLUDED_
#define _TC_TYPE_61FE304E_1B95_43AD_04F3_86A2FA0CF572_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_A_search_2021b_T,177552);

// DW_A_search_2021b_T
#ifndef _TC_TYPE_A48943F5_F4BB_D014_5700_A1270FD7E1E6_INCLUDED_
#define _TC_TYPE_A48943F5_F4BB_D014_5700_A1270FD7E1E6_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_A_search_2021b_T,28,56);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

#endif // _A_search_2021bInternal__h_INCLUDED