
// ****************** A_search_2021bCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_search_2021bCtrl__h_INCLUDED
#define _A_search_2021bCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CA_search_2021bDrvName "A_search_2021b"

#include "A_search_2021bW32Resource.h"
#include "A_search_2021bW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "A_search_2021bClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CA_search_2021bCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CA_search_2021bCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CA_search_2021bCtrl, CA_search_2021bClassFactory>
{
public:
	CA_search_2021bCtrl() : ITcOCFCtrlImpl<CA_search_2021bCtrl, CA_search_2021bClassFactory>(){}

	virtual ~CA_search_2021bCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_A_search_2021bCtrl)
DECLARE_NOT_AGGREGATABLE(CA_search_2021bCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CA_search_2021bCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _A_search_2021bCtrl__h_INCLUDED