
// ****************** A_search_2021bDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "A_search_2021bDrv.h"
#include "A_search_2021bClassFactory.h"
#include "A_search_2021bVersion.h"

DECLARE_GENERIC_DEVICE(A_search_2021bDRV)
#undef DEVICE_MAIN

IOSTATUS CA_search_2021bDrv::OnLoad( )
{
	TRACE(_T("CA_search_2021bClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CA_search_2021bClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CA_search_2021bDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CA_search_2021bDrv::A_search_2021b_GetVersion( )
{
	return(0);
}