// ****************** A_search_2021bServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_search_2021bServices__h_INCLUDED
#define _A_search_2021bServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "A_search_2021bVersion.h"
#define SRVNAME_A_search_2021b "A_search_2021b"

// TcCOM-ClassID of CTcComA_search_2021b: {D3CF0C5B-72ED-6E6F-924C-D778A775A0C2}
const CTCID CID_A_SEARCH_2021B = {0xD3CF0C5B, 0x72ED, 0x6E6F, {0x92, 0x4C, 0xD7, 0x78, 0xA7, 0x75, 0xA0, 0xC2}};
// TcCOM-ClassID of CFbA_search_2021b: {B90EACC0-9256-00E2-D3C8-232263C53674}
const CTCID CID_FB_A_SEARCH_2021B = {0xB90EACC0, 0x9256, 0x00E2, {0xD3, 0xC8, 0x23, 0x22, 0x63, 0xC5, 0x36, 0x74}};


#ifndef A_search_2021b_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_4E59F093_E425_1DD1_3496_F36BF2C5D01E_INCLUDED_)
#define _TC_TYPE_4E59F093_E425_1DD1_3496_F36BF2C5D01E_INCLUDED_
typedef struct _A_search_2021b_AdditionalInports
{
	double TcModuleInput_endNode;
	double TcModuleInput_xGoalEnd;
	double TcModuleInput_xRobotStart;
	double TcModuleInput_yGoalEnd;
	double TcModuleInput_yRobotStart;
} A_search_2021b_AdditionalInports, *PA_search_2021b_AdditionalInports;
#endif // !defined(_TC_TYPE_4E59F093_E425_1DD1_3496_F36BF2C5D01E_INCLUDED_)

#if !defined(_TC_TYPE_F943D866_5CCA_8252_A4DE_C3B2588A676E_INCLUDED_)
#define _TC_TYPE_F943D866_5CCA_8252_A4DE_C3B2588A676E_INCLUDED_
typedef double matrix_144_real_T[144];
#endif // !defined(_TC_TYPE_F943D866_5CCA_8252_A4DE_C3B2588A676E_INCLUDED_)

#if !defined(_TC_TYPE_68DD85F1_A51F_3ABA_6C1B_E27517924F89_INCLUDED_)
#define _TC_TYPE_68DD85F1_A51F_3ABA_6C1B_E27517924F89_INCLUDED_
typedef struct _A_search_2021b_AdditionalOutports
{
	matrix_144_real_T TcModuleOutput_xPointList;
	matrix_144_real_T TcModuleOutput_yPointList;
} A_search_2021b_AdditionalOutports, *PA_search_2021b_AdditionalOutports;
#endif // !defined(_TC_TYPE_68DD85F1_A51F_3ABA_6C1B_E27517924F89_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_7D36307D_4D1F_1968_DDE2_C60825B06EF5_INCLUDED_)
#define _TC_TYPE_7D36307D_4D1F_1968_DDE2_C60825B06EF5_INCLUDED_
typedef double matrix_720_real_T[720];
#endif // !defined(_TC_TYPE_7D36307D_4D1F_1968_DDE2_C60825B06EF5_INCLUDED_)

#if !defined(_TC_TYPE_84F14F01_1544_F8A7_772F_08338F3898B9_INCLUDED_)
#define _TC_TYPE_84F14F01_1544_F8A7_772F_08338F3898B9_INCLUDED_
typedef double matrix_20736_real_T[20736];
#endif // !defined(_TC_TYPE_84F14F01_1544_F8A7_772F_08338F3898B9_INCLUDED_)

#if !defined(_TC_TYPE_96759023_969C_4C54_91CF_54C1F04F81ED_INCLUDED_)
#define _TC_TYPE_96759023_969C_4C54_91CF_54C1F04F81ED_INCLUDED_
typedef double matrix_12_real_T[12];
#endif // !defined(_TC_TYPE_96759023_969C_4C54_91CF_54C1F04F81ED_INCLUDED_)

#if !defined(_TC_TYPE_61FE304E_1B95_43AD_04F3_86A2FA0CF572_INCLUDED_)
#define _TC_TYPE_61FE304E_1B95_43AD_04F3_86A2FA0CF572_INCLUDED_
typedef struct _B_A_search_2021b_T
{
	matrix_720_real_T closedList;
	double xRobotStart;
	double yRobotStart;
	double xGoalEnd;
	double yGoalEnd;
	double endNode;
	matrix_144_real_T xKoordinaten;
	matrix_144_real_T yKoordinaten;
	double startKnoten;
	matrix_20736_real_T A;
	matrix_12_real_T removeNode;
	matrix_144_real_T xKnoten;
	matrix_144_real_T yKnoten;
	matrix_144_real_T wayPointList;
} B_A_search_2021b_T, *PB_A_search_2021b_T;
#endif // !defined(_TC_TYPE_61FE304E_1B95_43AD_04F3_86A2FA0CF572_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("78189268-4DCA-E0BC-718B-D361EFD0087C", ITcA_search_2021b)



#endif // _A_search_2021bServices__h_INCLUDED
