
// ****************** FbA_search_2021b.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "FbA_search_2021b.h"


#include "ObjClassFactory.h"
using namespace TcMgSdk;

///////////////////////////////////////////////////////////////////////////////
// Definitions
///////////////////////////////////////////////////////////////////////////////
#ifdef _DEBUG
#define new DEBUG_NEW
#endif
#if TC_BUILD<=4024
DEFINE_THIS_FILE()
#endif

///////////////////////////////////////////////////////////////////////////////
// CFbA_search_2021b specific globals
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbA_search_2021b static members
///////////////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// CFbA_search_2021b implementation
///////////////////////////////////////////////////////////////////////////////
CFbA_search_2021b::CFbA_search_2021b()
{
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_CallerExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_CallerExceptions;


	
}

CFbA_search_2021b::~CFbA_search_2021b()
{

}

bool CFbA_search_2021b::FB_Main()
{

	bool fbMainResult = true;

	

	auto fpState = FpControl(FpCtrlSection::Update);
	((A_search_2021bModelClass*)A_search_2021b_Obj)->step();

	FpRestore(fpState);


	return fbMainResult;
}

void CFbA_search_2021b::_FB_Main(ST_FB_Main_FB_A_search_2021b* ST_Param)
{
	ST_Param->result = ((CFbA_search_2021b*)ST_Param->pInst)->FB_Main(  );
}

bool CFbA_search_2021b::FB_exit(bool bInCopyCode)
{

	bool fbExitResult = true;

	auto fpState = FpControl(FpCtrlSection::Init);
	((A_search_2021bModelClass*)A_search_2021b_Obj)->terminate();

	FpRestore(fpState);


	SingleInstanceRelease();
	__super::Exit(bInCopyCode);

	return fbExitResult;
}

void CFbA_search_2021b::_FB_exit(ST_FB_exit_FB_A_search_2021b* ST_Param)
{
	ST_Param->result = ((CFbA_search_2021b*)ST_Param->pInst)->FB_exit( ST_Param->bInCopyCode );
}

bool CFbA_search_2021b::FB_init(bool bInitRetains, bool bInCopyCode)
{

	bool fbInitResult = true;

	if(fbInitResult)
	{
		A_search_2021b_Obj = new A_search_2021bModelClass();
		memset(&(TcModuleOutput_xPointList),0,sizeof(TcModuleOutput_xPointList));
		memset(&(TcModuleOutput_yPointList),0,sizeof(TcModuleOutput_yPointList));
		TcModuleInput_endNode = 0;
		TcModuleInput_xGoalEnd = 0;
		TcModuleInput_xRobotStart = 0;
		TcModuleInput_yGoalEnd = 0;
		TcModuleInput_yRobotStart = 0;

		m_pData = nullptr;
		fbInitResult = __super::Init(0,TC_BUILD_MIN,bInitRetains,bInCopyCode);
		if (!fbInitResult)
		{
			error("__super::Init() did not succeed");
		}
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Init) = FpExcptCtrlSet::Prec53_CallerExceptions;
	GetFpExceptCtrlSet(TcMgSdk::FpCtrlSection::Update) = FpExcptCtrlSet::Prec53_CallerExceptions;


	}

	fbInitResult &= SingleInstanceLock(GUID_NULL);
	if(fbInitResult)
	{
		auto fpState = FpControl(FpCtrlSection::Init);
		((A_search_2021bModelClass*)A_search_2021b_Obj)->initialize();
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.endNode_PWORK = reinterpret_cast<PVOID>(&(TcModuleInput_endNode));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.xGoalEnd_PWORK = reinterpret_cast<PVOID>(&(TcModuleInput_xGoalEnd));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.xRobotStart_PWORK = reinterpret_cast<PVOID>(&(TcModuleInput_xRobotStart));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.yGoalEnd_PWORK = reinterpret_cast<PVOID>(&(TcModuleInput_yGoalEnd));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.yRobotStart_PWORK = reinterpret_cast<PVOID>(&(TcModuleInput_yRobotStart));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.xPointList_PWORK = reinterpret_cast<PVOID>(&(TcModuleOutput_xPointList));
		((A_search_2021bModelClass*)A_search_2021b_Obj)->A_search_2021b_DW.yPointList_PWORK = reinterpret_cast<PVOID>(&(TcModuleOutput_yPointList));

		FpRestore(fpState);
	}
	else
	{
		error("SingleInstanceLock() did not succeed");
	}

	return fbInitResult;
}

void CFbA_search_2021b::_FB_init(ST_FB_init_FB_A_search_2021b* ST_Param)
{
	ST_Param->result = ((CFbA_search_2021b*)ST_Param->pInst)->FB_init( ST_Param->bInitRetains, ST_Param->bInCopyCode );
}




BEGIN_FUNC_MAP_FB(CFbA_search_2021b)
	FUNC_ENTRY_LIB(VID_A_search_2021b, CID_FB_A_SEARCH_2021B , "FB_A_search_2021b" "__main", CFbA_search_2021b::_FB_Main)
FUNC_METHOD_ENTRY_LIB(VID_A_search_2021b,CID_FB_A_SEARCH_2021B , "FB_EXIT", "FB_A_search_2021b" "__FB_exit", CFbA_search_2021b::_FB_exit)
FUNC_METHOD_ENTRY_LIB(VID_A_search_2021b,CID_FB_A_SEARCH_2021B , "FB_INIT", "FB_A_search_2021b" "__FB_init", CFbA_search_2021b::_FB_init)

END_FUNC_MAP_FB()

DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbA_search_2021b)
{
	return CFbA_search_2021b::TcHandleFuncMap(mode, idx, idxcounter, pFncId, pipFnc, ppMethod, ppName, pSignature, pVersion);
}
