
// ****************** FbA_search_2021b.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbA_search_2021b__h_INCLUDED
#define _FbA_search_2021b__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "A_search_2021b.h"
#include "A_search_2021bInternal.h"

#include "A_search_2021bDuts.h"
#include "A_search_2021bInterfaces.h"
#include "A_search_2021bVersion.h"

class CFbA_search_2021b :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_A_search_2021b;}
	inline CLSID get_ClassID() {return CID_FB_A_SEARCH_2021B;}

	DECLARE_FUNC_MAP_FB()

	CFbA_search_2021b();
	~CFbA_search_2021b();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_A_search_2021b* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_A_search_2021b* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_A_search_2021b* ST_Param);


	double TcModuleInput_endNode;
	double TcModuleInput_xGoalEnd;
	double TcModuleInput_xRobotStart;
	double TcModuleInput_yGoalEnd;
	double TcModuleInput_yRobotStart;
	matrix_144_real_T TcModuleOutput_xPointList;
	matrix_144_real_T TcModuleOutput_yPointList;
	PVOID A_search_2021b_Obj;


};
TYPESIZE_VALIDATION2(CFbA_search_2021b,2360,2368);

			
#endif // _FbA_search_2021b__h_INCLUDED
			