// ****************** TcComA_search_2021b.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComA_search_2021b__h_INCLUDED
#define _TcComA_search_2021b__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcMatSimTcCom.h"
#include "A_search_2021b.h"
#include "A_search_2021bInternal.h"

#include "A_search_2021bInterfaces.h"
#include "A_search_2021bVersion.h"


class CTcComA_search_2021b :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcA_search_2021b
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()


	// Constructor
	CTcComA_search_2021b();

	// Destructor
	~CTcComA_search_2021b();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	HRESULT CheckAndAdaptCycleTimes();

	// ITcA_search_2021b
	HRESULT TCOMAPI step();



	A_search_2021b_AdditionalInports AdditionalInports;
	A_search_2021b_AdditionalOutports AdditionalOutports;
	A_search_2021bModelClass A_search_2021b_Obj;



};
			

#endif // _TcComA_search_2021b__h_INCLUDED