// ****************** A_SearchInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_SearchInterfaces__h_INCLUDED
#define _A_SearchInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "A_SearchServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_9379B375_26F9_13B0_F7DF_46BB4E9DF38E_INCLUDED_)
#define _TC_TYPE_9379B375_26F9_13B0_F7DF_46BB4E9DF38E_INCLUDED_
struct __declspec(novtable) ITcA_Search : ITcUnknown 
{
	virtual HRESULT TCOMAPI A_Search_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcA_Search, IID_ITcA_Search);
#endif // !defined(_TC_TYPE_9379B375_26F9_13B0_F7DF_46BB4E9DF38E_INCLUDED_)



#endif // _A_SearchInterfaces__h_INCLUDED
