// ****************** A_SearchDuts.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_SearchDuts__h_INCLUDED
#define _A_SearchDuts__h_INCLUDED
#include "A_SearchServices.h"



#endif // _A_SearchDuts__h_INCLUDED
