
// ****************** A_SearchCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_SearchCtrl__h_INCLUDED
#define _A_SearchCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CA_SearchDrvName "A_Search"

#include "A_SearchW32Resource.h"
#include "A_SearchW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "A_SearchClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CA_SearchCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CA_SearchCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CA_SearchCtrl, CA_SearchClassFactory>
{
public:
	CA_SearchCtrl() : ITcOCFCtrlImpl<CA_SearchCtrl, CA_SearchClassFactory>(){}

	virtual ~CA_SearchCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_A_SearchCtrl)
DECLARE_NOT_AGGREGATABLE(CA_SearchCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CA_SearchCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _A_SearchCtrl__h_INCLUDED