// ****************** A_SearchInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _A_SearchInternal__h_INCLUDED
#define _A_SearchInternal__h_INCLUDED

#include "rtwtypes.h"
#include "rtGetInf.h"
#include "rtGetNaN.h"
#include "rt_nonfinite.h"
#include "A_Search.h"
#include "A_Search_private.h"
#include "A_Search_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// B_A_Search_T
#ifndef _TC_TYPE_EAB177BA_3216_3E2F_6CC4_294DE5D49ED8_INCLUDED_
#define _TC_TYPE_EAB177BA_3216_3E2F_6CC4_294DE5D49ED8_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_A_Search_T,170768);

// DW_A_Search_T
#ifndef _TC_TYPE_9549F3C3_16B5_CA32_5E40_A0F01E45F170_INCLUDED_
#define _TC_TYPE_9549F3C3_16B5_CA32_5E40_A0F01E45F170_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_A_Search_T,32,64);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

#endif // _A_SearchInternal__h_INCLUDED