
// ****************** A_SearchDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "A_SearchDrv.h"
#include "A_SearchClassFactory.h"
#include "A_SearchVersion.h"

DECLARE_GENERIC_DEVICE(A_SearchDRV)
#undef DEVICE_MAIN

IOSTATUS CA_SearchDrv::OnLoad( )
{
	TRACE(_T("CA_SearchClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CA_SearchClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CA_SearchDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CA_SearchDrv::A_Search_GetVersion( )
{
	return(0);
}