
// ****************** A_SearchClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "A_SearchClassFactory.h"
#include "A_SearchServices.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComA_Search (PITCID pIid, PPVOID pipItf);


DEFINE_REPOSITORY_DRIVER(CA_SearchClassFactory, A_Search_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CA_SearchClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_A_Search,CID_A_SEARCH, SRVNAME_A_Search "!CTcComA_Search", Create_CTcComA_Search)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CA_SearchClassFactory)

END_FUNC_MAP()

CA_SearchClassFactory::CA_SearchClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_A_Search)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_A_Search));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(A_Search));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CA_SearchClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			