
// ****************** simpleObserverDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "simpleObserverDrv.h"
#include "simpleObserverClassFactory.h"
#include "simpleObserverVersion.h"

DECLARE_GENERIC_DEVICE(simpleObserverDRV)
#undef DEVICE_MAIN

IOSTATUS CsimpleObserverDrv::OnLoad( )
{
	TRACE(_T("CsimpleObserverClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CsimpleObserverClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CsimpleObserverDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CsimpleObserverDrv::simpleObserver_GetVersion( )
{
	return(0);
}