// ****************** simpleObserverInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserverInterfaces__h_INCLUDED
#define _simpleObserverInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "simpleObserverServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_DF61D718_14E5_8E71_4F10_1DB6B66F66D0_INCLUDED_)
#define _TC_TYPE_DF61D718_14E5_8E71_4F10_1DB6B66F66D0_INCLUDED_
struct __declspec(novtable) ITcsimpleObserver : ITcUnknown 
{
	virtual HRESULT TCOMAPI simpleObserver_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcsimpleObserver, IID_ITcsimpleObserver);
#endif // !defined(_TC_TYPE_DF61D718_14E5_8E71_4F10_1DB6B66F66D0_INCLUDED_)



#endif // _simpleObserverInterfaces__h_INCLUDED
