// ****************** simpleObserverW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserverCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_simpleObserverCtrl		=  {0x165A330D, 0xF9F7, 0x4728, {0x80, 0x47, 0x31, 0x19, 0x54, 0x0E, 0xBE, 0xBC}};
const   CLSID   LIBID_simpleObserverW32Lib	=  {0x1EF91325, 0xECE4, 0x4427, {0xB5, 0x50, 0xB2, 0x5A, 0x2A, 0xBF, 0xE5, 0xEF}};
const   CLSID   CLSID_simpleObserverCtrl   =  {0xE72B8247, 0x82B1, 0x4950, {0x8C, 0xD2, 0x26, 0x28, 0x58, 0x94, 0x78, 0x41}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_simpleObserverCtrl, CsimpleObserverCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CsimpleObserverCtrl>* pCsimpleObserverCtrl = new CComObject<CsimpleObserverCtrl>();
	if (pCsimpleObserverCtrl == NULL) return E_POINTER;
	return pCsimpleObserverCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
