<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TrackingController" Id="{012ed989-ad00-4074-8a95-3f6b38ed2b93}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TrackingController
VAR_INPUT
	xRobotPose : RobotPose;
	xRobotPoseRef : RobotPose;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	k1, k2, k3 : REAL;		// strictly positive control parameters
	vRef : REAL;			// reference linear velocity
	omegaRef : REAL;		// reference rotational velocity
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TrackingController">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>