
// ****************** FbKalmanObserver_R2021b.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbKalmanObserver_R2021b__h_INCLUDED
#define _FbKalmanObserver_R2021b__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "KalmanObserver_R2021bInternal.h"

#include "KalmanObserver_R2021bDuts.h"
#include "KalmanObserver_R2021bInterfaces.h"
#include "KalmanObserver_R2021bVersion.h"

class CFbKalmanObserver_R2021b :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_KalmanObserver_R2021b;}
	inline CLSID get_ClassID() {return CID_FB_KALMANOBSERVER_R2021B;}

	DECLARE_FUNC_MAP_FB()

	CFbKalmanObserver_R2021b();
	~CFbKalmanObserver_R2021b();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_KalmanObserver_R2021b* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_KalmanObserver_R2021b* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_KalmanObserver_R2021b* ST_Param);


	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InVThetaworld;
	double TcModuleInput_InVXworld;
	double TcModuleInput_InVYworld;
	double TcModuleInput_omegaToRobot;
	double TcModuleInput_vxToRobot;
	double TcModuleInput_vyToRobot;
	double TcModuleOutput_DEBUG;
	matrix_3_real_T TcModuleOutput_OutSimpleObsPose;
	matrix_3_real_T TcModuleOutput_OutSimpleObsPose1;
	double TcModuleOutput_version;


};
TYPESIZE_VALIDATION2(CFbKalmanObserver_R2021b,144,152);

			
#endif // _FbKalmanObserver_R2021b__h_INCLUDED
			