
// ****************** KalmanObserver_R2021bDrv.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "KalmanObserver_R2021bDrv.h"
#include "KalmanObserver_R2021bClassFactory.h"
#include "KalmanObserver_R2021bVersion.h"

DECLARE_GENERIC_DEVICE(KalmanObserver_R2021bDRV)
#undef DEVICE_MAIN

IOSTATUS CKalmanObserver_R2021bDrv::OnLoad( )
{
	TRACE(_T("CKalmanObserver_R2021bClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new CKalmanObserver_R2021bClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID CKalmanObserver_R2021bDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl CKalmanObserver_R2021bDrv::KalmanObserver_R2021b_GetVersion( )
{
	return(0);
}