// ****************** KalmanObserver_R2021bW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "KalmanObserver_R2021bCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_KalmanObserver_R2021bCtrl		=  {0x0753B4A4, 0x3965, 0x49B0, {0x86, 0xC3, 0x83, 0x7C, 0x7D, 0xDD, 0xD0, 0xFB}};
const   CLSID   LIBID_KalmanObserver_R2021bW32Lib	=  {0x8298F7BC, 0x11B7, 0x4A8E, {0xAF, 0x5C, 0x66, 0x5B, 0xB2, 0x41, 0x6A, 0x38}};
const   CLSID   CLSID_KalmanObserver_R2021bCtrl   =  {0x978C14A3, 0x0111, 0x41A3, {0x9E, 0x29, 0x2D, 0x4D, 0x9A, 0xB2, 0x99, 0xBF}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_KalmanObserver_R2021bCtrl, CKalmanObserver_R2021bCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CKalmanObserver_R2021bCtrl>* pCKalmanObserver_R2021bCtrl = new CComObject<CKalmanObserver_R2021bCtrl>();
	if (pCKalmanObserver_R2021bCtrl == NULL) return E_POINTER;
	return pCKalmanObserver_R2021bCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
