// ****************** KalmanObserver_R2021bW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "KalmanObserver_R2021bCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_KalmanObserver_R2021bCtrl		=  {0x12E619DC, 0xC13B, 0x45CA, {0x95, 0xEF, 0xA8, 0xAC, 0xC9, 0x50, 0x2E, 0x07}};
const   CLSID   LIBID_KalmanObserver_R2021bW32Lib	=  {0x4B3B9C70, 0xD392, 0x4E48, {0x98, 0x23, 0x5A, 0x85, 0x6C, 0x0B, 0x8E, 0xD6}};
const   CLSID   CLSID_KalmanObserver_R2021bCtrl   =  {0xEE87A42A, 0x5DE3, 0x4A17, {0xB6, 0x7D, 0x38, 0x44, 0x9C, 0xB4, 0xEA, 0x38}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_KalmanObserver_R2021bCtrl, CKalmanObserver_R2021bCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CKalmanObserver_R2021bCtrl>* pCKalmanObserver_R2021bCtrl = new CComObject<CKalmanObserver_R2021bCtrl>();
	if (pCKalmanObserver_R2021bCtrl == NULL) return E_POINTER;
	return pCKalmanObserver_R2021bCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
