
// ****************** KalmanObserver_R2021bDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bDrv__h_INCLUDED
#define _KalmanObserver_R2021bDrv__h_INCLUDED

#include "TcPch.h"

#define KalmanObserver_R2021bDRV_NAME			"KalmanObserver_R2021b"
#define KalmanObserver_R2021bDRV_Major			1
#define KalmanObserver_R2021bDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CKalmanObserver_R2021bDrv

#include "ObjDriver.h"

class CKalmanObserver_R2021bDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl KalmanObserver_R2021b_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( KalmanObserver_R2021bDRV)
	VxD_Service( KalmanObserver_R2021b_GetVersion		)
End_VxD_Service_Table


#endif // _KalmanObserver_R2021bDrv__h_INCLUDED