// ****************** KalmanObserver_R2021bInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bInternal__h_INCLUDED
#define _KalmanObserver_R2021bInternal__h_INCLUDED

#include "rtwtypes.h"
#include "KalmanObserver_R2021b.h"
#include "KalmanObserver_R2021b_private.h"
#include "KalmanObserver_R2021b_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// DW_KalmanObserver_R2021b_T
#ifndef _TC_TYPE_FB38A73A_CFC8_6DA7_1B9A_6DAA926610C9_INCLUDED_
#define _TC_TYPE_FB38A73A_CFC8_6DA7_1B9A_6DAA926610C9_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_KalmanObserver_R2021b_T,288,336);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// P_KalmanObserver_R2021b_T
#ifndef _TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_
#define _TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_
#endif
TYPESIZE_VALIDATION(P_KalmanObserver_R2021b_T,32);

// emxArray_real_T_4_KalmanObser_T
#ifndef _TC_TYPE_A671EEE6_CF36_4D46_1FFC_29604E6B5EB6_INCLUDED_
#define _TC_TYPE_A671EEE6_CF36_4D46_1FFC_29604E6B5EB6_INCLUDED_
#endif
TYPESIZE_VALIDATION(emxArray_real_T_4_KalmanObser_T,40);

#endif // _KalmanObserver_R2021bInternal__h_INCLUDED