// ****************** KalmanObserver_R2021bInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bInternal__h_INCLUDED
#define _KalmanObserver_R2021bInternal__h_INCLUDED

#include "rtwtypes.h"
#include "KalmanObserver_R2021b.h"
#include "KalmanObserver_R2021b_private.h"
#include "KalmanObserver_R2021b_types.h"
#include "multiword_types.h"
#include "rtmodel.h"


// DW_KalmanObserver_R2021b_T
#ifndef _TC_TYPE_885C126A_D8FB_42BC_8CA2_E284E8F51403_INCLUDED_
#define _TC_TYPE_885C126A_D8FB_42BC_8CA2_E284E8F51403_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_KalmanObserver_R2021b_T,552,592);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// P_KalmanObserver_R2021b_T
#ifndef _TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_
#define _TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_
#endif
TYPESIZE_VALIDATION(P_KalmanObserver_R2021b_T,32);

#endif // _KalmanObserver_R2021bInternal__h_INCLUDED