// ****************** KalmanObserver_R2021bW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "KalmanObserver_R2021bCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_KalmanObserver_R2021bCtrl		=  {0x174B9837, 0x69C9, 0x4B84, {0xA8, 0x20, 0x3B, 0x3D, 0x00, 0x04, 0x14, 0x01}};
const   CLSID   LIBID_KalmanObserver_R2021bW32Lib	=  {0x6C645B75, 0xAA04, 0x4658, {0x97, 0x1F, 0xB5, 0x8D, 0x5A, 0xD8, 0x95, 0x96}};
const   CLSID   CLSID_KalmanObserver_R2021bCtrl   =  {0x3503EAF8, 0x749E, 0x4E7E, {0xAC, 0x09, 0x5B, 0xD7, 0x9B, 0x56, 0xE4, 0xEA}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_KalmanObserver_R2021bCtrl, CKalmanObserver_R2021bCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CKalmanObserver_R2021bCtrl>* pCKalmanObserver_R2021bCtrl = new CComObject<CKalmanObserver_R2021bCtrl>();
	if (pCKalmanObserver_R2021bCtrl == NULL) return E_POINTER;
	return pCKalmanObserver_R2021bCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
