
// ****************** KalmanObserver_R2021bCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bCtrl__h_INCLUDED
#define _KalmanObserver_R2021bCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CKalmanObserver_R2021bDrvName "KalmanObserver_R2021b"

#include "KalmanObserver_R2021bW32Resource.h"
#include "KalmanObserver_R2021bW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "KalmanObserver_R2021bClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CKalmanObserver_R2021bCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CKalmanObserver_R2021bCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CKalmanObserver_R2021bCtrl, CKalmanObserver_R2021bClassFactory>
{
public:
	CKalmanObserver_R2021bCtrl() : ITcOCFCtrlImpl<CKalmanObserver_R2021bCtrl, CKalmanObserver_R2021bClassFactory>(){}

	virtual ~CKalmanObserver_R2021bCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_KalmanObserver_R2021bCtrl)
DECLARE_NOT_AGGREGATABLE(CKalmanObserver_R2021bCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CKalmanObserver_R2021bCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _KalmanObserver_R2021bCtrl__h_INCLUDED