// ****************** KalmanObserver_R2021bServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bServices__h_INCLUDED
#define _KalmanObserver_R2021bServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "KalmanObserver_R2021bVersion.h"
#define SRVNAME_KalmanObserver_R2021b "KalmanObserver_R2021b"

// TcCOM-ClassID of CTcComKalmanObserver_R2021b: {794560D8-C12F-050E-2B01-9FC5B0020BE2}
const CTCID CID_KALMANOBSERVER_R2021B = {0x794560D8, 0xC12F, 0x050E, {0x2B, 0x01, 0x9F, 0xC5, 0xB0, 0x02, 0x0B, 0xE2}};
// TcCOM-ClassID of CFbKalmanObserver_R2021b: {7FD2A10D-B2AA-E8F7-6D84-B5C041EF8E7E}
const CTCID CID_FB_KALMANOBSERVER_R2021B = {0x7FD2A10D, 0xB2AA, 0xE8F7, {0x6D, 0x84, 0xB5, 0xC0, 0x41, 0xEF, 0x8E, 0x7E}};


#ifndef KalmanObserver_R2021b_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)
#define _TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_
typedef double matrix_3_real_T[3];
#endif // !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)

#if !defined(_TC_TYPE_5E8BA1E2_95AA_E1B3_30C6_C831FBBD7787_INCLUDED_)
#define _TC_TYPE_5E8BA1E2_95AA_E1B3_30C6_C831FBBD7787_INCLUDED_
typedef struct _KalmanObserver_R2021b_AdditionalInports
{
	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InVThetaworld;
	double TcModuleInput_InVXworld;
	double TcModuleInput_InVYworld;
	double TcModuleInput_omegaToRobot;
	double TcModuleInput_vxToRobot;
	double TcModuleInput_vyToRobot;
} KalmanObserver_R2021b_AdditionalInports, *PKalmanObserver_R2021b_AdditionalInports;
#endif // !defined(_TC_TYPE_5E8BA1E2_95AA_E1B3_30C6_C831FBBD7787_INCLUDED_)

#if !defined(_TC_TYPE_25195608_AB1E_0BAD_AF90_8EE11433080F_INCLUDED_)
#define _TC_TYPE_25195608_AB1E_0BAD_AF90_8EE11433080F_INCLUDED_
typedef struct _KalmanObserver_R2021b_AdditionalOutports
{
	double TcModuleOutput_DEBUG;
	matrix_3_real_T TcModuleOutput_OutKalmanObsPose;
	matrix_3_real_T TcModuleOutput_OutSimpleObsPose;
	double TcModuleOutput_version;
} KalmanObserver_R2021b_AdditionalOutports, *PKalmanObserver_R2021b_AdditionalOutports;
#endif // !defined(_TC_TYPE_25195608_AB1E_0BAD_AF90_8EE11433080F_INCLUDED_)

#if !defined(_TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_)
#define _TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_
typedef struct _P_KalmanObserver_R2021b_T
{
	double Constant_Value;
	double CameraDelay_InitialCondition;
	double DelayOneStep1_InitialCondition;
	double Integrator_IC;
} P_KalmanObserver_R2021b_T, *PP_KalmanObserver_R2021b_T;
#endif // !defined(_TC_TYPE_C6C8F93A_E54D_0B86_4D42_C2718AE18617_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_3737846F_E1D6_FF59_67F2_2DADB20D8528_INCLUDED_)
#define _TC_TYPE_3737846F_E1D6_FF59_67F2_2DADB20D8528_INCLUDED_
typedef double matrix_6_real_T[6];
#endif // !defined(_TC_TYPE_3737846F_E1D6_FF59_67F2_2DADB20D8528_INCLUDED_)

#if !defined(_TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_)
#define _TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_
typedef double matrix_9_real_T[9];
#endif // !defined(_TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_)

#if !defined(_TC_TYPE_2D468F76_7D24_0D43_D379_F1A71820B9BF_INCLUDED_)
#define _TC_TYPE_2D468F76_7D24_0D43_D379_F1A71820B9BF_INCLUDED_
typedef struct _KalmanObserver_R2021b_KalmanObserver_R2021b_DW1_Type
{
	matrix_6_real_T CameraDelay_DSTATE;
	matrix_3_real_T DelayOneStep1_DSTATE;
	matrix_3_real_T estPoseOld;
	matrix_3_real_T xHatOld;
	matrix_9_real_T P;
	matrix_3_real_T oldCamData;
} KalmanObserver_R2021b_KalmanObserver_R2021b_DW1_Type, *PKalmanObserver_R2021b_KalmanObserver_R2021b_DW1_Type;
#endif // !defined(_TC_TYPE_2D468F76_7D24_0D43_D379_F1A71820B9BF_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("89117D3B-752F-3140-FF92-386A08272C89", ITcKalmanObserver_R2021b)



#endif // _KalmanObserver_R2021bServices__h_INCLUDED
