// ****************** KalmanObserver_R2021bInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _KalmanObserver_R2021bInterfaces__h_INCLUDED
#define _KalmanObserver_R2021bInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "KalmanObserver_R2021bServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_89117D3B_752F_3140_FF92_386A08272C89_INCLUDED_)
#define _TC_TYPE_89117D3B_752F_3140_FF92_386A08272C89_INCLUDED_
struct __declspec(novtable) ITcKalmanObserver_R2021b : ITcUnknown 
{
	virtual HRESULT TCOMAPI KalmanObserver_R2021b_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcKalmanObserver_R2021b, IID_ITcKalmanObserver_R2021b);
#endif // !defined(_TC_TYPE_89117D3B_752F_3140_FF92_386A08272C89_INCLUDED_)



#endif // _KalmanObserver_R2021bInterfaces__h_INCLUDED
