// ****************** TcComKalmanObserver_R2021b.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComKalmanObserver_R2021b__h_INCLUDED
#define _TcComKalmanObserver_R2021b__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcMatSimTcCom.h"
#include "KalmanObserver_R2021bInternal.h"

#include "KalmanObserver_R2021bInterfaces.h"
#include "KalmanObserver_R2021bVersion.h"


class CTcComKalmanObserver_R2021b :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcKalmanObserver_R2021b
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()


	// Constructor
	CTcComKalmanObserver_R2021b();

	// Destructor
	~CTcComKalmanObserver_R2021b();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	HRESULT CheckAndAdaptCycleTimes();

	// ITcKalmanObserver_R2021b
	HRESULT TCOMAPI KalmanObserver_R2021b_step();



	KalmanObserver_R2021b_AdditionalInports AdditionalInports;
	KalmanObserver_R2021b_AdditionalOutports AdditionalOutports;



};
			

#endif // _TcComKalmanObserver_R2021b__h_INCLUDED