<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="ZEROS" Id="{449177e9-991c-40f0-879f-55ab898b2896}" SpecialFunc="None">
    <Declaration><![CDATA[//Fills an array of LREAL of varible length with zeros
FUNCTION ZEROS
VAR_IN_OUT
	arr: ARRAY [*] OF LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[FILL(arr := arr,val := 0.0);]]></ST>
    </Implementation>
    <LineIds Name="ZEROS">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>