
// ****************** FbsimpleObserver.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbsimpleObserver__h_INCLUDED
#define _FbsimpleObserver__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "simpleObserverInternal.h"

#include "simpleObserverDuts.h"
#include "simpleObserverInterfaces.h"
#include "simpleObserverVersion.h"

class CFbsimpleObserver :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_simpleObserver;}
	inline CLSID get_ClassID() {return CID_FB_SIMPLEOBSERVER;}

	DECLARE_FUNC_MAP_FB()

	CFbsimpleObserver();
	~CFbsimpleObserver();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_simpleObserver* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_simpleObserver* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_simpleObserver* ST_Param);


	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InVThetaworld;
	double TcModuleInput_InVXworld;
	double TcModuleInput_InVYworld;
	double TcModuleOutput_DEBUG;
	matrix_3_real_T TcModuleOutput_OutEstimatedPose;
	double TcModuleOutput_version;


};
TYPESIZE_VALIDATION2(CFbsimpleObserver,96,104);

			
#endif // _FbsimpleObserver__h_INCLUDED
			