// ****************** simpleObserverW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserverCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_simpleObserverCtrl		=  {0xB2C5E38A, 0xF41D, 0x4DA6, {0xA4, 0x85, 0x46, 0xFC, 0x37, 0x17, 0xA1, 0xCB}};
const   CLSID   LIBID_simpleObserverW32Lib	=  {0x6A62ED87, 0x1122, 0x4480, {0x88, 0x04, 0xD9, 0xC7, 0xCB, 0x51, 0x76, 0x3F}};
const   CLSID   CLSID_simpleObserverCtrl   =  {0xAC506BAB, 0xD150, 0x40AB, {0x84, 0xF4, 0xF8, 0x59, 0x86, 0x95, 0x2E, 0xDA}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_simpleObserverCtrl, CsimpleObserverCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CsimpleObserverCtrl>* pCsimpleObserverCtrl = new CComObject<CsimpleObserverCtrl>();
	if (pCsimpleObserverCtrl == NULL) return E_POINTER;
	return pCsimpleObserverCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
