// ****************** simpleObserverInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserverInternal__h_INCLUDED
#define _simpleObserverInternal__h_INCLUDED

#include "rtwtypes.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "simpleObserver.h"
#include "simpleObserver_private.h"
#include "simpleObserver_types.h"


// DW_simpleObserver_T
#ifndef _TC_TYPE_F6E50A61_EE91_9597_D274_39FBAA860C3B_INCLUDED_
#define _TC_TYPE_F6E50A61_EE91_9597_D274_39FBAA860C3B_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_simpleObserver_T,440,464);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// P_simpleObserver_T
#ifndef _TC_TYPE_009AB79F_853F_30BE_51E0_69FB8CF7E8C4_INCLUDED_
#define _TC_TYPE_009AB79F_853F_30BE_51E0_69FB8CF7E8C4_INCLUDED_
#endif
TYPESIZE_VALIDATION(P_simpleObserver_T,32);

#endif // _simpleObserverInternal__h_INCLUDED