
// ****************** simpleObserverDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserverDrv__h_INCLUDED
#define _simpleObserverDrv__h_INCLUDED

#include "TcPch.h"

#define simpleObserverDRV_NAME			"simpleObserver"
#define simpleObserverDRV_Major			1
#define simpleObserverDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CsimpleObserverDrv

#include "ObjDriver.h"

class CsimpleObserverDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl simpleObserver_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( simpleObserverDRV)
	VxD_Service( simpleObserver_GetVersion		)
End_VxD_Service_Table


#endif // _simpleObserverDrv__h_INCLUDED