
// ****************** FbsimpleObserver2.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _FbsimpleObserver2__h_INCLUDED
#define _FbsimpleObserver2__h_INCLUDED



#include "TcMatSimPou.h"
#include "TcGeneratedPou.h"
#include "simpleObserver2Internal.h"

#include "simpleObserver2Duts.h"
#include "simpleObserver2Interfaces.h"
#include "simpleObserver2Version.h"

class CFbsimpleObserver2 :
	public TcMatSim::GeneratedPou
{
public:

	inline void operator()() {this->FB_Main();}
	inline GUID get_VersionID() {return VID_simpleObserver2;}
	inline CLSID get_ClassID() {return CID_FB_SIMPLEOBSERVER2;}

	DECLARE_FUNC_MAP_FB()

	CFbsimpleObserver2();
	~CFbsimpleObserver2();
	bool FB_Main();
	static void _FB_Main(ST_FB_Main_FB_simpleObserver2* ST_Param);
	bool FB_exit(bool bInCopyCode);
	static void _FB_exit(ST_FB_exit_FB_simpleObserver2* ST_Param);
	bool FB_init(bool bInitRetains, bool bInCopyCode);
	static void _FB_init(ST_FB_init_FB_simpleObserver2* ST_Param);


	matrix_3x3_real_T TcModuleInput_Estimator1_K;
	bool TcModuleInput_Estimator1_Reset;
	char TcModuleInput_Estimator1_cameraDelayCylces;
	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InVThetaworld;
	double TcModuleInput_InVXworld;
	double TcModuleInput_InVYworld;
	matrix_3_real_T TcModuleOutput_OutEstimatedPose;
	double TcModuleOutput_ThetaDenormalized;
	double TcModuleOutput_version;
	PVOID PsimpleObserver2_M;


};
TYPESIZE_VALIDATION2(CFbsimpleObserver2,184,192);

			
#endif // _FbsimpleObserver2__h_INCLUDED
			