// ****************** simpleObserver2Internal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2Internal__h_INCLUDED
#define _simpleObserver2Internal__h_INCLUDED

#include "rtwtypes.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "simpleObserver2.h"
#include "simpleObserver2_private.h"
#include "simpleObserver2_types.h"


// B_simpleObserver2_T
#ifndef _TC_TYPE_3380F9D8_0F93_8AA4_2B2A_ED5A95AE4123_INCLUDED_
#define _TC_TYPE_3380F9D8_0F93_8AA4_2B2A_ED5A95AE4123_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_simpleObserver2_T,272);

// DW_simpleObserver2_T
#ifndef _TC_TYPE_26FF7851_A029_74C3_99E0_928CA48A5E65_INCLUDED_
#define _TC_TYPE_26FF7851_A029_74C3_99E0_928CA48A5E65_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_simpleObserver2_T,400,432);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// X_simpleObserver2_T
#ifndef _TC_TYPE_215CB797_EAAD_C81F_4E4B_84CF0E28D3B7_INCLUDED_
#define _TC_TYPE_215CB797_EAAD_C81F_4E4B_84CF0E28D3B7_INCLUDED_
#endif
TYPESIZE_VALIDATION(X_simpleObserver2_T,24);

// int_T
#ifndef _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#define _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#endif
TYPESIZE_VALIDATION(int_T,4);

#endif // _simpleObserver2Internal__h_INCLUDED