// ****************** simpleObserver2W32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2Ctrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_simpleObserver2Ctrl		=  {0x21A55DB2, 0xF100, 0x4147, {0xBA, 0x25, 0xE8, 0xEA, 0x45, 0x15, 0x7F, 0x3D}};
const   CLSID   LIBID_simpleObserver2W32Lib	=  {0xA58C75B4, 0xBB88, 0x4DA5, {0x84, 0xF5, 0x40, 0x25, 0xF7, 0x8F, 0x51, 0x4A}};
const   CLSID   CLSID_simpleObserver2Ctrl   =  {0xA67ECE02, 0x5A4E, 0x471A, {0xA7, 0x63, 0x19, 0x6A, 0x1C, 0x89, 0x16, 0x9C}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_simpleObserver2Ctrl, CsimpleObserver2Ctrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CsimpleObserver2Ctrl>* pCsimpleObserver2Ctrl = new CComObject<CsimpleObserver2Ctrl>();
	if (pCsimpleObserver2Ctrl == NULL) return E_POINTER;
	return pCsimpleObserver2Ctrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
