
// ****************** simpleObserver2Drv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2Drv__h_INCLUDED
#define _simpleObserver2Drv__h_INCLUDED

#include "TcPch.h"

#define simpleObserver2DRV_NAME			"simpleObserver2"
#define simpleObserver2DRV_Major			1
#define simpleObserver2DRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CsimpleObserver2Drv

#include "ObjDriver.h"

class CsimpleObserver2Drv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl simpleObserver2_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( simpleObserver2DRV)
	VxD_Service( simpleObserver2_GetVersion		)
End_VxD_Service_Table


#endif // _simpleObserver2Drv__h_INCLUDED