// ****************** simpleObserver2Internal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2Internal__h_INCLUDED
#define _simpleObserver2Internal__h_INCLUDED

#include "rtwtypes.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "simpleObserver2.h"
#include "simpleObserver2_private.h"
#include "simpleObserver2_types.h"
#include "zero_crossing_types.h"


// B_simpleObserver2_T
#ifndef _TC_TYPE_73FD96A7_D550_7E96_CEE2_1953181D0505_INCLUDED_
#define _TC_TYPE_73FD96A7_D550_7E96_CEE2_1953181D0505_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_simpleObserver2_T,296);

// DW_simpleObserver2_T
#ifndef _TC_TYPE_B603CC15_F136_A9C3_2312_49C9BEC94637_INCLUDED_
#define _TC_TYPE_B603CC15_F136_A9C3_2312_49C9BEC94637_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_simpleObserver2_T,2480,2520);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// PrevZCX_simpleObserver2_T
#ifndef _TC_TYPE_1AF8EC94_C28C_FA3E_090B_A00F190D26A5_INCLUDED_
#define _TC_TYPE_1AF8EC94_C28C_FA3E_090B_A00F190D26A5_INCLUDED_
#endif
TYPESIZE_VALIDATION(PrevZCX_simpleObserver2_T,1);

// X_simpleObserver2_T
#ifndef _TC_TYPE_215CB797_EAAD_C81F_4E4B_84CF0E28D3B7_INCLUDED_
#define _TC_TYPE_215CB797_EAAD_C81F_4E4B_84CF0E28D3B7_INCLUDED_
#endif
TYPESIZE_VALIDATION(X_simpleObserver2_T,24);

// ZCSigState
#ifndef _TC_TYPE_261539EC_8FE9_2BBE_18ED_5AE24AF80B3D_INCLUDED_
#define _TC_TYPE_261539EC_8FE9_2BBE_18ED_5AE24AF80B3D_INCLUDED_
#endif
TYPESIZE_VALIDATION(ZCSigState,1);

// int_T
#ifndef _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#define _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#endif
TYPESIZE_VALIDATION(int_T,4);

#endif // _simpleObserver2Internal__h_INCLUDED