// ****************** simpleObserver2Interfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2Interfaces__h_INCLUDED
#define _simpleObserver2Interfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "simpleObserver2Services.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_A98A1411_C399_C245_D300_12BBDE4B2E4C_INCLUDED_)
#define _TC_TYPE_A98A1411_C399_C245_D300_12BBDE4B2E4C_INCLUDED_
struct __declspec(novtable) ITcsimpleObserver2 : ITcUnknown 
{
	virtual HRESULT TCOMAPI simpleObserver2_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcsimpleObserver2, IID_ITcsimpleObserver2);
#endif // !defined(_TC_TYPE_A98A1411_C399_C245_D300_12BBDE4B2E4C_INCLUDED_)



#endif // _simpleObserver2Interfaces__h_INCLUDED
