// ****************** simpleObserver2W32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2Ctrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_simpleObserver2Ctrl		=  {0xC82A4604, 0x8551, 0x44A4, {0xAF, 0x8D, 0x47, 0x6D, 0xCF, 0x3E, 0x77, 0xBE}};
const   CLSID   LIBID_simpleObserver2W32Lib	=  {0x3B3F5264, 0xE495, 0x4BFF, {0xB5, 0x73, 0x04, 0x68, 0x04, 0x88, 0xFD, 0x94}};
const   CLSID   CLSID_simpleObserver2Ctrl   =  {0x1F418868, 0x87A7, 0x41B1, {0x82, 0xB7, 0x81, 0x84, 0x60, 0x1D, 0x39, 0x8D}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_simpleObserver2Ctrl, CsimpleObserver2Ctrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CsimpleObserver2Ctrl>* pCsimpleObserver2Ctrl = new CComObject<CsimpleObserver2Ctrl>();
	if (pCsimpleObserver2Ctrl == NULL) return E_POINTER;
	return pCsimpleObserver2Ctrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
