
// ****************** simpleObserver2ClassFactory.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2ClassFactory.h"
#include "simpleObserver2Services.h"
#include "TcGeneratedPou.h"

HRESULT TCOMAPI Create_CTcComsimpleObserver2 (PITCID pIid, PPVOID pipItf);
DECLARE_FUNCMAP_CREATOR(HandleFuncMap_CFbsimpleObserver2);


DEFINE_REPOSITORY_DRIVER(CsimpleObserver2ClassFactory, simpleObserver2_LibraryIdNameStr)

// ITComClassFactory
BEGIN_CLASS_MAP(CsimpleObserver2ClassFactory)
	CLASS_ENTRY_LIB_RT_CREATOR(VID_simpleObserver2,CID_SIMPLEOBSERVER2, SRVNAME_simpleObserver2 "!CTcComsimpleObserver2", Create_CTcComsimpleObserver2)

END_CLASS_MAP()

BEGIN_FUNC_MAP(CsimpleObserver2ClassFactory)
	FUNC_ENTRY_FB_CREATOR(HandleFuncMap_CFbsimpleObserver2)

END_FUNC_MAP()

CsimpleObserver2ClassFactory::CsimpleObserver2ClassFactory() : CObjClassFactory()
{
	#ifndef TC_USE_TMX_EXTENSION
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_simpleObserver2)); 
	#else
		TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_simpleObserver2));
	#if defined(TCDBG_UNIT_VERSION)
		TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(simpleObserver2));
	#endif //defined(TCDBG_UNIT_VERSION)
	#endif
}

IMPLEMENT_MGCLASSFACTORY_CONNECT(CsimpleObserver2ClassFactory,new TcMatSim::ServiceProvider(TC_BUILD_MIN))
			