
// ****************** simpleObserver2Ctrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2Ctrl__h_INCLUDED
#define _simpleObserver2Ctrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CsimpleObserver2DrvName "simpleObserver2"

#include "simpleObserver2W32Resource.h"
#include "simpleObserver2W32.h"
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2ClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CsimpleObserver2Ctrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CsimpleObserver2Ctrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CsimpleObserver2Ctrl, CsimpleObserver2ClassFactory>
{
public:
	CsimpleObserver2Ctrl() : ITcOCFCtrlImpl<CsimpleObserver2Ctrl, CsimpleObserver2ClassFactory>(){}

	virtual ~CsimpleObserver2Ctrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_simpleObserver2Ctrl)
DECLARE_NOT_AGGREGATABLE(CsimpleObserver2Ctrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CsimpleObserver2Ctrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _simpleObserver2Ctrl__h_INCLUDED