// ****************** TcComsimpleObserver2.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _TcComsimpleObserver2__h_INCLUDED
#define _TcComsimpleObserver2__h_INCLUDED


#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcMatSimTcCom.h"
#include "simpleObserver2Internal.h"

#include "simpleObserver2Interfaces.h"
#include "simpleObserver2Version.h"


class CTcComsimpleObserver2 :
	public TcMatSim::GeneratedTcCom,
	public ITcWatchSource,
	public ITcCyclic,
	public ITcPostCyclic,
	public ITcADI,
	public ITcsimpleObserver2
{
public:
	DECLARE_IUNKNOWN_DERIVED()
	DECLARE_ITCOMOBJECT_SETSTATE()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJDATAAREA_MAP()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_PARA()
	DECLARE_ITCADI()
	DECLARE_IPERSIST_LIB()


	// Constructor
	CTcComsimpleObserver2();

	// Destructor
	~CTcComsimpleObserver2();

	HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT TCOMAPI PostCyclicUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);
	HRESULT Update(ITcTask* ipTask, ULONG_PTR context);
	HRESULT CheckAndAdaptCycleTimes();

	// ITcsimpleObserver2
	HRESULT TCOMAPI simpleObserver2_step();



	simpleObserver2_AdditionalInports AdditionalInports;
	simpleObserver2_AdditionalOutports AdditionalOutports;
	RT_MODEL_simpleObserver2_T* PsimpleObserver2_M;



};
			

#endif // _TcComsimpleObserver2__h_INCLUDED