
// ****************** simpleObserver2withKalmanDrv.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanDrv__h_INCLUDED
#define _simpleObserver2withKalmanDrv__h_INCLUDED

#include "TcPch.h"

#define simpleObserver2withKalmanDRV_NAME			"simpleObserver2withKalman"
#define simpleObserver2withKalmanDRV_Major			1
#define simpleObserver2withKalmanDRV_Minor			0

#if defined DEVICE_MAIN		// is supposed to be __cplusplus

#define DEVICE_CLASS			CsimpleObserver2withKalmanDrv

#include "ObjDriver.h"

class CsimpleObserver2withKalmanDrv : public CObjDriver
{
public:
	virtual IOSTATUS	OnLoad( );
	virtual VOID		OnUnLoad( );
	
	//////////////////////////////////////////////////////
	// VxD-Services exported by this driver
	static unsigned long _cdecl simpleObserver2withKalman_GetVersion( );
};

#endif	// #if defined DEVICE_MAIN

Begin_VxD_Service_Table( simpleObserver2withKalmanDRV)
	VxD_Service( simpleObserver2withKalman_GetVersion		)
End_VxD_Service_Table


#endif // _simpleObserver2withKalmanDrv__h_INCLUDED