// ****************** simpleObserver2withKalmanW32.cpp *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2withKalmanCtrl.h"
#include "TcSysW32_i.c"

CComModule _Module;

const   CLSID   IID_simpleObserver2withKalmanCtrl		=  {0x3114241B, 0xEBB0, 0x4B07, {0xB5, 0x34, 0xF7, 0x6C, 0x5E, 0xA4, 0x18, 0x6C}};
const   CLSID   LIBID_simpleObserver2withKalmanW32Lib	=  {0x5BBDBC7E, 0xA77A, 0x455A, {0x87, 0xF5, 0x7D, 0xB1, 0x14, 0x72, 0x4D, 0x10}};
const   CLSID   CLSID_simpleObserver2withKalmanCtrl   =  {0x8F5FB611, 0x64A6, 0x4EBB, {0x87, 0x18, 0x3B, 0x19, 0xDE, 0xED, 0xB1, 0xF6}};

BEGIN_OBJECT_MAP(ObjectMap)
OBJECT_ENTRY(CLSID_simpleObserver2withKalmanCtrl, CsimpleObserver2withKalmanCtrl)
END_OBJECT_MAP()

/////////////////////////////////////////////////////////////////////////////
// DLL Entry Point

extern "C"
BOOL WINAPI DllMain(HANDLE hInstance, DWORD dwReason, LPVOID /*lpReserved*/)
{
	if (dwReason == DLL_PROCESS_ATTACH)
	{
		_Module.Init(ObjectMap, (HINSTANCE)hInstance);
#ifndef UNDER_CE
		DisableThreadLibraryCalls((HINSTANCE)hInstance);
#endif
	}
	else if (dwReason == DLL_PROCESS_DETACH)
		_Module.Term();
	return TRUE;    // ok
}

/////////////////////////////////////////////////////////////////////////////
// Used to determine whether the DLL can be unloaded by OLE

STDAPI DllCanUnloadNow(void)
{
	return (_Module.GetLockCount()==0) ? S_OK : S_FALSE;
}

/////////////////////////////////////////////////////////////////////////////
// Returns a class factory to create an object of the requested type

STDAPI DllGetClassObject(REFCLSID rclsid, REFIID riid, LPVOID* ppv)
{
	return _Module.GetClassObject(rclsid, riid, ppv);
}

/////////////////////////////////////////////////////////////////////////////
// DllRegisterServer - Adds entries to the system registry

STDAPI DllRegisterServer(void)
{
	// registers object, typelib and all interfaces in typelib
	return _Module.RegisterServer(TRUE);
}

/////////////////////////////////////////////////////////////////////////////
// DllUnregisterServer - Removes entries from the system registry

STDAPI DllUnregisterServer(void)
{
	_Module.UnregisterServer();
	return S_OK;
}

/////////////////////////////////////////////////////////////////////////////
STDAPI DllGetTcCtrl(ITcCtrl** ppCtrl)
{
	if ( ppCtrl == NULL )
		return E_POINTER;

	CComObject<CsimpleObserver2withKalmanCtrl>* pCsimpleObserver2withKalmanCtrl = new CComObject<CsimpleObserver2withKalmanCtrl>();
	if (pCsimpleObserver2withKalmanCtrl == NULL) return E_POINTER;
	return pCsimpleObserver2withKalmanCtrl->QueryInterface(IID_ITcCtrl, reinterpret_cast<void**>(ppCtrl));
}
