
// ****************** simpleObserver2withKalmanClassFactory.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanClassFactory__h_INCLUDED
#define _simpleObserver2withKalmanClassFactory__h_INCLUDED

#include "TcMatSimCFServiceProvider.h"

class CsimpleObserver2withKalmanClassFactory : public CObjClassFactory
{
protected:
	DECLARE_REPOSITORY_DRIVER()
public:
	CsimpleObserver2withKalmanClassFactory();

	// ITComClassFactory
	DECLARE_CLASS_MAP()
	DECLARE_FUNC_MAP()

	DECLARE_MGCLASSFACTORY_CONNECT()
};

#endif // _simpleObserver2withKalmanClassFactory__h_INCLUDED
			