// ****************** simpleObserver2withKalmanServices.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanServices__h_INCLUDED
#define _simpleObserver2withKalmanServices__h_INCLUDED

#include "TcInterfaces.h"
#include "TcServices.h"
#include "TcGeneratedClass.h"
#include "TcGeneratedTcCom.h"
#include "stdio.h"

#include "TcGeneratedCFInterfaces.h"

#include "simpleObserver2withKalmanVersion.h"
#define SRVNAME_simpleObserver2withKalman "simpleObserver2withKalman"

// TcCOM-ClassID of CTcComsimpleObserver2withKalman: {48E6D4BF-C23F-E4C0-0B01-1A38BA041B5E}
const CTCID CID_SIMPLEOBSERVER2WITHKALMAN = {0x48E6D4BF, 0xC23F, 0xE4C0, {0x0B, 0x01, 0x1A, 0x38, 0xBA, 0x04, 0x1B, 0x5E}};
// TcCOM-ClassID of CFbsimpleObserver2withKalman: {5F2EA86C-2373-A691-E219-607CF6F4FCF4}
const CTCID CID_FB_SIMPLEOBSERVER2WITHKALMAN = {0x5F2EA86C, 0x2373, 0xA691, {0xE2, 0x19, 0x60, 0x7C, 0xF6, 0xF4, 0xFC, 0xF4}};


#ifndef simpleObserver2withKalman_IGNORE_SERVICES_TYPES
#if !defined(_TC_TYPE_001C11BC_8935_E2E2_173B_24C634D18FCC_INCLUDED_)
#define _TC_TYPE_001C11BC_8935_E2E2_173B_24C634D18FCC_INCLUDED_
typedef double matrix_3x3_real_T[3][3];
#endif // !defined(_TC_TYPE_001C11BC_8935_E2E2_173B_24C634D18FCC_INCLUDED_)

#if !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)
#define _TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_
typedef double matrix_3_real_T[3];
#endif // !defined(_TC_TYPE_610A2D24_A761_AE0B_B518_D70554B2A821_INCLUDED_)

#if !defined(_TC_TYPE_D4227F8F_EA6A_6825_D114_4AB0D381641B_INCLUDED_)
#define _TC_TYPE_D4227F8F_EA6A_6825_D114_4AB0D381641B_INCLUDED_
typedef struct _simpleObserver2withKalman_AdditionalInports
{
	matrix_3x3_real_T TcModuleInput_Estimator1_K;
	bool TcModuleInput_Estimator1_Reset;
	unsigned char reserved1[7];
	double TcModuleInput_Estimator1_UseSimpleNotKalman;
	char TcModuleInput_Estimator1_cameraDelayCylces;
	unsigned char reserved2[7];
	matrix_3_real_T TcModuleInput_InCameraPose;
	double TcModuleInput_InVThetaworld;
	double TcModuleInput_InVXworld;
	double TcModuleInput_InVYworld;
} simpleObserver2withKalman_AdditionalInports, *PsimpleObserver2withKalman_AdditionalInports;
#endif // !defined(_TC_TYPE_D4227F8F_EA6A_6825_D114_4AB0D381641B_INCLUDED_)

#if !defined(_TC_TYPE_B7CF558A_3988_4F70_C76C_C65E58D8BDFA_INCLUDED_)
#define _TC_TYPE_B7CF558A_3988_4F70_C76C_C65E58D8BDFA_INCLUDED_
typedef struct _simpleObserver2withKalman_AdditionalOutports
{
	matrix_3_real_T TcModuleOutput_OutEstimatedPose;
	double TcModuleOutput_version;
} simpleObserver2withKalman_AdditionalOutports, *PsimpleObserver2withKalman_AdditionalOutports;
#endif // !defined(_TC_TYPE_B7CF558A_3988_4F70_C76C_C65E58D8BDFA_INCLUDED_)

#if !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)
#define _TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_
typedef CHAR STRING127[128];
#endif // !defined(_TC_TYPE_18071995_0000_0000_0000_00010000007F_INCLUDED_)

#if !defined(_TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_)
#define _TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_
typedef double matrix_9_real_T[9];
#endif // !defined(_TC_TYPE_72A91784_953A_FD09_4E66_5B1F6549B49B_INCLUDED_)

#if !defined(_TC_TYPE_3F657963_352E_5669_4373_6E540CF2633C_INCLUDED_)
#define _TC_TYPE_3F657963_352E_5669_4373_6E540CF2633C_INCLUDED_
typedef struct _B_simpleObserver2withKalman_T
{
	matrix_3_real_T InCameraPose;
	matrix_3_real_T Odometry;
	matrix_3_real_T CameraDelay;
	double InVXworld;
	double InVYworld;
	double InVThetaworld;
	matrix_3_real_T Memory;
	double Subtract;
	matrix_3_real_T CameraDelay1;
	matrix_9_real_T K;
	double UseSimpleNotKalman;
	matrix_3_real_T Sum;
	matrix_3_real_T Sum1;
	matrix_3_real_T xHat;
	matrix_9_real_T H;
	matrix_9_real_T Pout;
	double initOut;
	matrix_3_real_T Switch;
	matrix_3_real_T Product1;
	matrix_3_real_T SwitchObserver;
	matrix_3_real_T TmpSignalConversionAtSFunctionI;
	char cameraDelayCylces;
	bool Reset;
	bool newCamDataArrived;
	unsigned char reserved1[5];
} B_simpleObserver2withKalman_T, *PB_simpleObserver2withKalman_T;
#endif // !defined(_TC_TYPE_3F657963_352E_5669_4373_6E540CF2633C_INCLUDED_)

#if !defined(_TC_TYPE_D2B1C544_B16A_6FF0_760C_9246A80BD380_INCLUDED_)
#define _TC_TYPE_D2B1C544_B16A_6FF0_760C_9246A80BD380_INCLUDED_
typedef struct _X_simpleObserver2withKalman_T
{
	matrix_3_real_T Integrator_CSTATE;
} X_simpleObserver2withKalman_T, *PX_simpleObserver2withKalman_T;
#endif // !defined(_TC_TYPE_D2B1C544_B16A_6FF0_760C_9246A80BD380_INCLUDED_)

#if !defined(_TC_TYPE_0A7316D4_BFFE_C731_DEA9_110616289DBB_INCLUDED_)
#define _TC_TYPE_0A7316D4_BFFE_C731_DEA9_110616289DBB_INCLUDED_
typedef double matrix_300_real_T[300];
#endif // !defined(_TC_TYPE_0A7316D4_BFFE_C731_DEA9_110616289DBB_INCLUDED_)

#if !defined(_TC_TYPE_73F20E95_7E1E_9778_BFCF_9EEDDB800935_INCLUDED_)
#define _TC_TYPE_73F20E95_7E1E_9778_BFCF_9EEDDB800935_INCLUDED_
typedef struct _simpleObserver2withKalman_simpleObserver2withKalman_DW1_Type
{
	matrix_300_real_T CameraDelay_DSTATE;
	matrix_300_real_T CameraDelay1_DSTATE;
	matrix_3_real_T Memory_PreviousInput;
	double Subtract_DWORK1;
	matrix_3_real_T xHatOld;
	matrix_9_real_T P;
	matrix_3_real_T oldCamData;
} simpleObserver2withKalman_simpleObserver2withKalman_DW1_Type, *PsimpleObserver2withKalman_simpleObserver2withKalman_DW1_Type;
#endif // !defined(_TC_TYPE_73F20E95_7E1E_9778_BFCF_9EEDDB800935_INCLUDED_)

#if !defined(_TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_)
#define _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
typedef LONG int_T;
#endif // !defined(_TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_)

#if !defined(_TC_TYPE_DC2E12DB_A866_5FA1_E5F3_E193501D76E5_INCLUDED_)
#define _TC_TYPE_DC2E12DB_A866_5FA1_E5F3_E193501D76E5_INCLUDED_
#pragma pack(push,1)
typedef struct _simpleObserver2withKalman_simpleObserver2withKalman_DW3_Type
{
	int_T Integrator_IWORK;
	bool init_not_empty;
} simpleObserver2withKalman_simpleObserver2withKalman_DW3_Type, *PsimpleObserver2withKalman_simpleObserver2withKalman_DW3_Type;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_DC2E12DB_A866_5FA1_E5F3_E193501D76E5_INCLUDED_)


#endif

TCOM_DECL_INTERFACE("70E7B399-0346-A1A9-C048-899D180BD78A", ITcsimpleObserver2withKalman)



#endif // _simpleObserver2withKalmanServices__h_INCLUDED
