// ****************** simpleObserver2withKalmanInternal.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanInternal__h_INCLUDED
#define _simpleObserver2withKalmanInternal__h_INCLUDED

#include "rtwtypes.h"
#include "multiword_types.h"
#include "rtmodel.h"
#include "simpleObserver2withKalman.h"
#include "simpleObserver2withKalman_private.h"
#include "simpleObserver2withKalman_types.h"
#include "zero_crossing_types.h"


// B_simpleObserver2withKalman_T
#ifndef _TC_TYPE_3F657963_352E_5669_4373_6E540CF2633C_INCLUDED_
#define _TC_TYPE_3F657963_352E_5669_4373_6E540CF2633C_INCLUDED_
#endif
TYPESIZE_VALIDATION(B_simpleObserver2withKalman_T,560);

// DW_simpleObserver2withKalman_T
#ifndef _TC_TYPE_327FD5CF_4B55_0965_44DB_D1F74DC7B586_INCLUDED_
#define _TC_TYPE_327FD5CF_4B55_0965_44DB_D1F74DC7B586_INCLUDED_
#endif
TYPESIZE_VALIDATION2(DW_simpleObserver2withKalman_T,5000,5040);

// PVOID
#ifndef _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#define _TC_TYPE_18071995_0000_0000_0000_000000000018_INCLUDED_
#endif
TYPESIZE_VALIDATION2(PVOID,4,8);

// PrevZCX_simpleObserver2withKa_T
#ifndef _TC_TYPE_27C7FE3A_8B90_7AF2_31E5_D1FE0962CBBA_INCLUDED_
#define _TC_TYPE_27C7FE3A_8B90_7AF2_31E5_D1FE0962CBBA_INCLUDED_
#endif
TYPESIZE_VALIDATION(PrevZCX_simpleObserver2withKa_T,1);

// X_simpleObserver2withKalman_T
#ifndef _TC_TYPE_D2B1C544_B16A_6FF0_760C_9246A80BD380_INCLUDED_
#define _TC_TYPE_D2B1C544_B16A_6FF0_760C_9246A80BD380_INCLUDED_
#endif
TYPESIZE_VALIDATION(X_simpleObserver2withKalman_T,24);

// ZCSigState
#ifndef _TC_TYPE_261539EC_8FE9_2BBE_18ED_5AE24AF80B3D_INCLUDED_
#define _TC_TYPE_261539EC_8FE9_2BBE_18ED_5AE24AF80B3D_INCLUDED_
#endif
TYPESIZE_VALIDATION(ZCSigState,1);

// int_T
#ifndef _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#define _TC_TYPE_7CC55797_31DD_5AB7_296E_2DB7BE6FD367_INCLUDED_
#endif
TYPESIZE_VALIDATION(int_T,4);

#endif // _simpleObserver2withKalmanInternal__h_INCLUDED