
// ****************** simpleObserver2withKalmanCtrl.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanCtrl__h_INCLUDED
#define _simpleObserver2withKalmanCtrl__h_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define CsimpleObserver2withKalmanDrvName "simpleObserver2withKalman"

#include "simpleObserver2withKalmanW32Resource.h"
#include "simpleObserver2withKalmanW32.h"
#include "TcPch.h"
#pragma hdrstop

#include "simpleObserver2withKalmanClassFactory.h"
#include "TcOCFCtrlImpl.h"

class CsimpleObserver2withKalmanCtrl :	public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<CsimpleObserver2withKalmanCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<CsimpleObserver2withKalmanCtrl, CsimpleObserver2withKalmanClassFactory>
{
public:
	CsimpleObserver2withKalmanCtrl() : ITcOCFCtrlImpl<CsimpleObserver2withKalmanCtrl, CsimpleObserver2withKalmanClassFactory>(){}

	virtual ~CsimpleObserver2withKalmanCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_simpleObserver2withKalmanCtrl)
DECLARE_NOT_AGGREGATABLE(CsimpleObserver2withKalmanCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(CsimpleObserver2withKalmanCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif // _simpleObserver2withKalmanCtrl__h_INCLUDED