// ****************** simpleObserver2withKalmanInterfaces.h *************************
// Generated by TE140x-TargetForMatlabSimulink  2.3.1.1
// MATLAB 9.11.0.2022996 (R2021b) Update 4 (win64)
// TwinCAT 3.1.4024.0
// TwinCAT Target 2.3.1.1
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef _simpleObserver2withKalmanInterfaces__h_INCLUDED
#define _simpleObserver2withKalmanInterfaces__h_INCLUDED
#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "simpleObserver2withKalmanServices.h"

// interfaces provided by this driver
#if !defined(_TC_TYPE_70E7B399_0346_A1A9_C048_899D180BD78A_INCLUDED_)
#define _TC_TYPE_70E7B399_0346_A1A9_C048_899D180BD78A_INCLUDED_
struct __declspec(novtable) ITcsimpleObserver2withKalman : ITcUnknown 
{
	virtual HRESULT TCOMAPI simpleObserver2withKalman_step() = 0;
};
_TCOM_SMARTPTR_TYPEDEF(ITcsimpleObserver2withKalman, IID_ITcsimpleObserver2withKalman);
#endif // !defined(_TC_TYPE_70E7B399_0346_A1A9_C048_899D180BD78A_INCLUDED_)



#endif // _simpleObserver2withKalmanInterfaces__h_INCLUDED
